#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli core type get
cli::import cli core type unmodified

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Emit the name of all user defined types used to compose a type.
    
Description
    Argument \$1 - \$n represent a type.

    Echo the name of all user defined types encountered by walking
    the type and its fields recursively. 
EOF
}

::cli::core::type::emit::inline() {

    # strip modifiers 
    ::cli::core::type::unmodified::inline "$@"

    # skip builtin types
    if ${REPLY_CLI_CORE_TYPE_IS_BUILTIN}; then
        return
    fi

    # emit the user defined type
    echo ${MAPFILE[@]}

    # recurse using the type of each of the user defined type's fields
    local -n CLI_TYPE_REF="${REPLY}"
    for FIELD_TYPE in "${CLI_TYPE_REF[@]}"; do
        ::cli::core::type::emit::inline ${FIELD_TYPE}
    done
}

self_test() {
    diff <( ${CLI_COMMAND[@]} -- string ) - < /dev/null
    diff <( ${CLI_COMMAND[@]} -- integer ) - < /dev/null
    diff <( ${CLI_COMMAND[@]} -- map ) - < /dev/null
    diff <( ${CLI_COMMAND[@]} -- array ) - < /dev/null
    diff <( ${CLI_COMMAND[@]} -- map_of string ) - < /dev/null
    diff <( ${CLI_COMMAND[@]} -- map_of map_of string ) - < /dev/null

    declare -A CLI_TYPE_FLOAT=(
        [decimal]="integer" 
        [places]="integer" 
        [integer]="integer"
    )

    diff <( ${CLI_COMMAND[@]} -- map_of float ) - <<< 'float'

    declare -A CLI_TYPE_CONSTANT=(
        [value]="float" 
        [alt]="float" 
        [name]="string"
    )

    diff <( ${CLI_COMMAND[@]} -- constant | sort -u ) - <<< $'constant\nfloat'
}
