#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import_inline cli core type is-scaler

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is builtin.

Description
    Return true if the type is:
    
        string
        integer
        boolean
        map
        array

    otherwise false.
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::is_builtin::inline() {
    local -a type=( ${1-} )

    if ::cli::core::type::is_scaler::inline "$@"; then
        true
    else
        case ${type} in
            'map') ;&
            'array') true ;;
            *) false ;;
        esac
    fi
}

main() {
    ::cli::core::type::is_builtin::inline "$@"
}

self_test() {
    main 'boolean' || cli::assert
    main 'string' || cli::assert
    main 'integer' || cli::assert
    main 'map' || cli::assert
    main 'array' || cli::assert

    ! main 'user_defined' || cli::assert
    ! main 'map_of string' || cli::assert
}
