#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is modified.

Description
    Return true if the type is modified by:
    
        map_of

    otherwise false.

    A modified type is an associative array where the value is the name
    of a variable whose type is the element type of the modified type.
    For example a 'map_of map_of string' is a map whose values point to
    yet another map whose values point to strings.
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::is_modified::inline() {
    local -a type=( ${1-} )

    if (( ${#type[@]} > 1 )); then
        [[ ${type} == 'map_of' ]] || cli::assert
        true
    else
        ! [[ ${type} == 'map_of' ]] || cli::assert
        false
    fi
}

main() {
    ::cli::core::type::is_modified::inline "$@"
}

self_test() {

    main 'map_of map' || cli::assert
    ! main 'map' || cli::assert
}
