#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import cli-assert

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND}
    
Summary
    Return true if type is a scaler.

Description
    Return true if the type is:
    
        string
        integer
        boolean

    otherwise false.
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::is_scaler::inline() {
    : ${arg_type?"Unexpected missing 'type'."}

    local -a type=( ${arg_type} )

    case ${type} in
        'integer') ;&
        'boolean') ;&
        'string') true ;;
        *) false ;;
    esac
}

self_test() {
    set +e
    arg_type=boolean inline
    assert::ok 'boolean'

    arg_type=string inline
    assert::ok 'string'

    arg_type=integer inline
    assert::ok 'integer'

    arg_type=map inline 
    assert::failed 'map'

    arg_type=user_defined inline
    assert::failed 'user_defined'

    arg_type='map_of string' inline
    assert::failed 'map_of string'
    set -e
}

cli::main "$@"
