#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is a scaler.

Description
    Return true if the type is:
    
        string
        integer
        boolean

    otherwise false.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::core::type::is_scaler::inline() {

    if (( $# != 1 )); then
        false
    else
        case "$1" in
            'integer') ;&
            'boolean') ;&
            'string') true ;;
            *) false ;;
        esac
    fi
}

self_test() {
    ${CLI_COMMAND[@]} -- boolean || cli::assert
    ${CLI_COMMAND[@]} -- string || cli::assert
    ${CLI_COMMAND[@]} -- integer || cli::assert

    ! ${CLI_COMMAND[@]} -- map  || cli::assert
    ! ${CLI_COMMAND[@]} -- user_defined  || cli::assert
    ! ${CLI_COMMAND[@]} -- map_of string || cli::assert
    ! ${CLI_COMMAND[@]} -- string string || cli::assert
}
