#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is a scaler.

Description
    Return true if the type is:
    
        string
        integer
        boolean

    otherwise false.
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::is_scaler::inline() {
    local -a TYPE=( ${1-''} )

    case ${TYPE} in
        'integer') ;&
        'boolean') ;&
        'string') true ;;
        *) false ;;
    esac
}

main() {
    ::cli::core::type::is_scaler::inline "$@"
}

self_test() {
    main 'boolean' || cli::assert
    main 'string' || cli::assert
    main 'integer' || cli::assert

    ! main 'map' || cli::assert
    ! main 'user_defined' || cli::assert
    ! main 'map_of string' || cli::assert
}
