#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli core type is-builtin
cli::import cli core type is-modified

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is user defined.

Description
    Return false if the type is:
    
        string
        integer
        boolean
        map
        array

    also return false if the type is modified:

        map_of

    otherwise, return true.
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::is_user_defined::inline() {   
    if ::cli::core::type::is_builtin::inline "$@" || \
        ::cli::core::type::is_modified::inline "$@"; then
        false
    else
        true
    fi
}

main() {
    ::cli::core::type::is_user_defined::inline "$@"
}

self_test() {
    main 'user_defined' || cli::assert

    ! main 'boolean' || cli::assert
    ! main 'string' || cli::assert
    ! main 'integer' || cli::assert
    ! main 'map' || cli::assert
    ! main 'array' || cli::assert
    ! main 'map_of string' || cli::assert
}
