#!/usr/bin/env bash
source $(cli loader)
cli::import_inline cli core type is-scaler
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return true if type is a builtin.

Description
    Return true if the type is:
    
        string
        integer
        boolean
        map
        array

Arguments
    --type      [Required]  : Type

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    local -a type=( ${arg_type} )

    if arg_type=${type} ::cli::core::type::is_scaler::inline; then
        true
    else
        case ${type} in
            'map') ;&
            'array') true ;;
            *) false ;;
        esac
    fi
}

self_test() {
    arg_type=boolean inline boolean
    assert::ok 'boolean'

    arg_type=string inline 
    assert::ok 'string'

    arg_type=integer inline 
    assert::ok 'integer'

    arg_type=map inline 
    assert::ok 'map'

    arg_type=array inline 
    assert::ok 'array'

    set +e
    arg_type='map_of string' inline
    assert::failed 'map_of string'

    arg_type=user_defined inline
    assert::failed 'user_defined'
    set -e
}

cli::load "$@"
