#!/usr/bin/env bash
source $(cli loader)
cli::import_group
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return true if type is modified.

Description
    Return true if the type is modified by:
    
        map_of

    otherwise false.

    A modified type is an associative array where the value is the name
    of a variable whose type is the element type of the modified type.
    For example a 'map_of map_of string' is a map whose values point to
    yet another map whose values point to strings.

Arguments
    ${CLI_CORE_TYPE_ARG_TYPE}

Global Arguments
    ${CLI_GLOBAL_ARG_HELP}
    ${CLI_GLOBAL_ARG_SELF_TEST}
EOF
}

inline() {
    local -a type=( ${arg_type} )

    if (( ${#type[@]} > 1 )); then
        cli::assert "[[ ${type} == 'map_of' ]]"
        true
    else
        cli::assert "! [[ ${type} == 'map_of' ]]"
        false
    fi
}

self_test() {

    arg_type='map_of map' inline 
    assert::ok 'map_of map'

    set +e
    arg_type='map' inline 
    assert::failed 'map'
    set -e
}

cli::main "$@"
