#!/usr/bin/env bash
source $(cli loader)
cli::import_group
cli::import_inline cli core type is-builtin
cli::import_inline cli core type is-modified
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return true if type is user defined.

Description
    Return false if the type is:
    
        string
        integer
        boolean
        map
        array

    also return false if the type is modified:

        map_of

    otherwise, return true.

Arguments
    ${CLI_CORE_TYPE_ARG_NAME}

Global Arguments
    ${CLI_GLOBAL_ARG_HELP}
    ${CLI_GLOBAL_ARG_SELF_TEST}
EOF
}

inline() {   
    if arg_type=${arg_type} ::cli::core::type::is_builtin::inline || \
        arg_type=${arg_type} ::cli::core::type::is_modified::inline; then
        false
    else
        true
    fi
}

self_test() {
    arg_type=user_defined inline 
    assert::ok 'user_defined'

    set +e
    arg_type=boolean inline boolean
    assert::failed 'boolean'

    arg_type=string inline 
    assert::failed 'string'

    arg_type=integer inline 
    assert::failed 'integer'

    arg_type=map inline 
    assert::failed 'map'

    arg_type=array inline 
    assert::failed 'array'

    arg_type='map_of string' inline 
    assert::failed 'map_of string'
    set -e
}

cli::load "$@"
