#!/usr/bin/env bash
source $(cli loader)
cli::import_inline cli core type is-builtin
cli::import_inline cli core type is-modified
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return true if type is user defined.

Description
    Return false if the type is not:
    
        string
        integer
        boolean
        map
        array

    Return false if the type is modified:

        map_of

    Otherwise, return true.

Arguments
    --type -t     [Require] : Variable type.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    local -a type=( ${arg_type} )
   
    if arg_type=${type} ::cli::core::type::is_builtin::inline || \
        arg_type=${type} ::cli::core::type::is_modified::inline; then
        false
    else
        true
    fi
}

self_test() {
    arg_type=user_defined inline 
    assert::ok 'user_defined'

    set +e
    arg_type=boolean inline boolean
    assert::failed 'boolean'

    arg_type=string inline 
    assert::failed 'string'

    arg_type=integer inline 
    assert::failed 'integer'

    arg_type=map inline 
    assert::failed 'map'

    arg_type=array inline 
    assert::failed 'array'
    set -e
}

cli::load "$@"
