#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return the type less one modifier or the type if self it is unmodified.

Description
    Return a type less one modifiers. For example, the unmodified type of
    
        map_of map_of string

    becomes 

        map_of string
EOF
}

cli::meta::declare() {
    cli::core::type::import
}

::cli::core::type::unmodify::inline() {
    set ${1-}

    if (( $# > 1 )); then
        shift
    fi

    echo "$@"
}

main() {
    ::cli::core::type::unmodify::inline "$@"
}

self_test() {
    [[ "$(main 'boolean')" == 'boolean' ]] || cli::assert
    [[ "$(main 'map_of map_of boolean')" == 'map_of boolean' ]] || cli::assert
}
