#!/usr/bin/env bash
source $(cli loader)
cli::import_group
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return the unmodified type of a type.

Description
    Return a type without any modifiers. For example, the unmodified type of
    
        map_of map_of string

    is 

        string

Arguments
    ${CLI_CORE_TYPE_ARG_NAME}

Global Arguments
    ${CLI_GLOBAL_ARG_HELP}
    ${CLI_GLOBAL_ARG_SELF_TEST}
EOF
}

inline() {
    set ${arg_type}
    eval "echo \$$#"
}

self_test() {
    assert::eq $(arg_type=boolean inline) 'boolean'
    assert::eq $(arg_type='map_of boolean' inline) 'boolean'
}

cli::load "$@"
