#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return the unmodified type of a type.

Description
    Return a type without any modifiers. For example, the unmodified type of
    
        map_of map_of string

    is 

        string

Arguments
    --type        [Require] : Type

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    set ${arg_type}
    eval "echo \$$#"
}

self_test() {
    assert::eq $(arg_type=boolean inline) 'boolean'
    assert::eq $(arg_type='map_of boolean' inline) 'boolean'
}

cli::load "$@"
