#!/usr/bin/env bash
source $(cli loader)
cli::import_group
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Return the unmodified type of a type.

Description
    Return a type without any modifiers. For example, the unmodified type of
    
        map_of map_of string

    is 

        map_of string

Arguments
    ${CLI_CORE_TYPE_ARG_TYPE}
    --recurse -r     [Flag] : Strip all modifiers. 
    
Global Arguments
    ${CLI_GLOBAL_ARG_HELP_FLAG}
    ${CLI_GLOBAL_ARG_SELF_TEST_FLAG}
EOF
}

cli::post_imports() {
    CLI_META_0_ALIAS+=([r]="recurse" )
    CLI_META_0_ALLOW+=([recurse]="0" )
    CLI_META_0_DEFAULT+=([recurse]="false" )
    CLI_META_0_IMPLICIT_VALUE+=([recurse]="true" )
}

inline() {
    : ${arg_type?}
    : ${arg_recurse:=false}

    set ${arg_type}

    if ${arg_recurse}; then
        eval "echo \$$#"
    else
        if (( $# > 1 )); then
            shift
        fi

        echo "$@"
    fi
}

self_test() {
    assert::eq \
        "$(arg_type=boolean inline)" \
        'boolean'

    assert::eq \
        "$(arg_type='map_of map_of boolean' inline)" \
        'map_of boolean'

    assert::eq \
        "$(arg_type='map_of map_of boolean' arg_recurse=true inline)" \
        'boolean'
}

cli::main "$@"
