#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli core type is-modified

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return the unmodified type of a type.

Description
    Return a type without any modifiers. For example, the unmodified type of
    
        map_of map_of string

    is 

        string
EOF
}

::cli::core::type::unmodified::inline() {
    local type=( "$@" )

    while ::cli::core::type::is_modified::inline "$@"; do
        shift
    done

    (( $# == 1 )) || cli::assert "Unable to unmodify type ${type}."

    REPLY="$1"
}

self_test() {
    [[ "$(${CLI_COMMAND[@]} ---reply boolean)" == 'boolean' ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply map_of map_of boolean)" == 'boolean' ]] || cli::assert
    # [[ "$(${CLI_COMMAND[@]} ---reply string string)" == $'string\nstring' ]] || cli::assert
}
