#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}

Summary
    Emit a minimum implementation of initialize.

Description
    Emits a minimum implementation of initialize that supports 
    '-h', '--help', and '--self-test'.
EOF
}

initialize() {
    : ${arg_help:=false}
    : ${arg_self_test:=false}

    while (( $# > 0 )); do
        case $1 in
            '-h') ;& '--help') arg_help=true ;;
            '--self-test') arg_self_test=true ;;
            *) echo "Unexpected argument '$1'."; exit 1 ;;
        esac

        shift
    done
}

main() {
    echo foo > /dev/stderr
    declare -f initialize
}

cli::main "$@"