#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}

Summary
    Converts a stream of cli names to unix names.

Description
    Converts a stream of cli names to unix names. Fails if any of the
    cli names do not match regex ${CLI_REGEX_NAME}.

Arguments
    --result -r             : Array to store command name. Default: RESULT.
EOF
    cat << EOF

Examples
    Convert '.foo-bar' 'baz' to '.foo-bar' 'baz'
        ${CLI_COMMAND} <<< $'.foo-bar\nbaz'

EOF
}

cli::meta::declare() {
    cli::meta::add_optional result 'RESULT'
}

inline() {
    local -a _result=()
    local -n ref_result=${arg_result:-RESULT}

    local args=( "$@" )
    while (( $# > 0 )); do
        if [[ ! "$1" =~ ${CLI_REGEX_NAME} ]]; then
            cli::fail "Unexpected cli name \"$1\"" \
                "found in \"${args[@]}\"" \
                "does not match regex ${CLI_REGEX_NAME}."
        fi
        ref_result+=( "${1//-/_}" )
        shift
    done
}

main() {
    declare -a RESULT=()

    mapfile -t
    inline "${MAPFILE[@]}"
    IFS=$'\n'; echo "${RESULT[*]}"; unset IFS
}

self_test() {
    ${CLI_COMMAND} <<< $'.foo-bar-baz\nbaz' \
    | assert::pipe_eq \
        ".foo_bar_baz" \
        "baz"

    assert::fails "${CLI_COMMAND} <<< $'foo_bar'"
}

cli::main "$@"
