#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import_inline cli subshell temp file

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Create a temporary fifo, set REPLY to its path, and register a trap to
    unlink the fifo upon subshell exit.

Description
    The first argument is the name of the variable to return the path to the
    temporary fifo. The default is REPLY.

    Upon exit a trap will run to delete the temporary fifo.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::subshell::temp::fifo::inline "$@"
}

::cli::subshell::temp::fifo::inline() {
    declare -n REPLY_REF=${1-'REPLY'}
    ::cli::subshell::temp::file::inline "$@"
    rm -f "${REPLY_REF}"
    mkfifo "${REPLY_REF}"
}

self_test() {

    mapfile -t < <(
        # create a temp file
        main
        [[ -p "${REPLY}" ]] || cli::assert
        echo "${REPLY}"

        # create a temp fifo to explicitly delete
        main
        [[ -p "${REPLY}" ]] || cli::assert
        rm "${REPLY}"

        # create a temp file returned via a custom name
        main MY_REPLY
        [[ -p "${MY_REPLY}" ]] || cli::assert
        echo "${MY_REPLY}"
    )

    (( ${#MAPFILE[@]} == 2 )) || cli::assert
    [[ ! -a "${MAPFILE[0]}" ]] || cli::assert
    [[ ! -a "${MAPFILE[1]}" ]] || cli::assert
}
