#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import_inline cli subshell on-exit

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Create a temporary file, set REPLY to its path, and register a trap to
    unlink the file upon subshell exit.

Description
    The first argument is the name of the variable to return the path to the
    temporary file. The default is REPLY.

    Upon exit a trap will run to delete the temporary file.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::subshell::temp::file::inline "$@"
}

::cli::subshell::temp::file::inline() {

    # create and return a temporary file
    local -n REPLY_REF=${1-'REPLY'}
    REPLY_REF=$(mktemp "${2-"${TMPDIR:-/tmp/}"}cli-XXXXXXXX")

    # record the temporary file 
    declare -gA "CLI_SUBSHELL_TEMP_FILE_${BASHPID}+=()"
    local -n CLI_SUBSHELL_TEMP_FILE_BASHPID=CLI_SUBSHELL_TEMP_FILE_${BASHPID}

    # cleanup
    if (( ${#CLI_SUBSHELL_TEMP_FILE_BASHPID[@]} == 0 )); then
        ::cli::subshell::temp::file::on_exit() {
            local -n CLI_SUBSHELL_TEMP_FILE_BASHPID=CLI_SUBSHELL_TEMP_FILE_${BASHPID}

            # unlink files/directories
            for FILE in ${!CLI_SUBSHELL_TEMP_FILE_BASHPID[@]}; do
                if [[ ! -a "${FILE}" ]]; then
                    :
                elif [[ -d "${FILE}" ]]; then
                    rm -f -r "${FILE}"
                else
                    rm -f "${FILE}"
                fi
            done
        }

        ::cli::subshell::on_exit::inline \
            ::cli::subshell::temp::file::on_exit
    fi

    CLI_SUBSHELL_TEMP_FILE_BASHPID+=( ["${REPLY_REF}"]='true' )
}

self_test() {

    mapfile -t < <(
        # create a temp file
        main
        [[ -f "${REPLY}" ]] || cli::assert
        echo "${REPLY}"

        # create a temp file returned via a custom name
        main MY_REPLY
        [[ -f "${MY_REPLY}" ]] || cli::assert
        echo "${MY_REPLY}"

        # create a temp file to explicitly delete
        main
        [[ -f "${REPLY}" ]] || cli::assert
        rm "${REPLY}"
    )

    (( ${#MAPFILE[@]} == 2 )) || cli::assert
    [[ ! -a "${MAPFILE[0]}" ]] || cli::assert
    [[ ! -a "${MAPFILE[1]}" ]] || cli::assert
}
