#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    
Description
EOF
    cat << EOF

Examples
    Emit a predicate that test if a path is a group.
        cli find --cli cli --type g \
            | ${CLI_COMMAND[@]}
EOF
}

emit::parallel_cat() {
    { 
        echo "cat"
        while read; do 
            emit::process_substitution "${REPLY}"
        done | emit::indent
    } | emit::continuation
}

parallel_cat() {
    emit::parallel_cat | source /dev/stdin
}

main() {
    # time {
    #     while read; do
    #         echo "cli emit define-initialize --cli \"${REPLY}\""
    #     done
    # } \
    # | parallel_cat \
    # | cli::emit::section 'Initializers'

    time while read; do cli emit define-initialize --cli "${REPLY}"; done \
        | cli::emit::section 'Initializers'
}

self_test() (
    return
)

cli::main "$@"