#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    
Description

Arguments

Global Arguments
    --help -h           [Flag] : Show this message and exit.
    --self-test         [Flag] : Runs a self test.

Examples
    Emit a predicate that test if a path is a group.
        cli find --cli cli --type g \
            | ${CLI_COMMAND}
EOF
}

emit::parallel_cat() {
    { 
        echo "cat"
        while read; do 
            emit::process_substitution "${REPLY}"
        done | emit::indent
    } | emit::continuation
}

parallel_cat() {
    emit::parallel_cat | source /dev/stdin
}

main() {
    # time {
    #     while read; do
    #         echo "cli emit define-initialize --cli \"${REPLY}\""
    #     done
    # } \
    # | parallel_cat \
    # | cli::emit::section 'Initializers'

    time while read; do cli emit define-initialize --cli "${REPLY}"; done \
        | cli::emit::section 'Initializers'
}

self_test() (
    return
)

cli::main "$@"