#!/usr/bin/env bash-cli-shim
cli() { 
    if [[ "${1-}" == '---root' ]]; then
        echo "${BASH_SOURCE%/*}/src"
        return
    fi

    local CLI_NAME="${FUNCNAME}"
    cli::loader::shim "$@"
}
