#!/usr/bin/env bash-cli-shim
jwt() {
    if [ ! -v CLI_LOADER_SHIM_ROOT_JWT ]; then
        readonly CLI_LOADER_SHIM_ROOT_JWT="$( cd $(dirname ${BASH_SOURCE}); pwd)/tool/jwt"
    fi

    BASH_ARGV0="${CLI_LOADER_SHIM_ROOT_JWT}"
    cli::loader::shim "${FUNCNAME}" "$@"
}
