#!/usr/bin/env bash-cli-shim
jwt() {

    # CLI_ROOT
    local -n CLI_ROOT="CLI_LOADER_SHIM_ROOT_JWT"
    if [ ! -v CLI_ROOT ]; then
        readonly CLI_LOADER_SHIM_ROOT_JWT="$( cd $(dirname ${BASH_SOURCE}); pwd)/tool/jwt"
    fi
    
    while true; do
        case "$1" in
            '---root')
                echo "${CLI_ROOT}" ;;
            *) break ;;
        esac
        return
    done

    cli::loader::shim "${FUNCNAME}" "$@"
}
