#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::source cli core type is-modified
cli::source cli core type is-scaler
cli::source cli core type is-builtin

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if the type is map, array, or is modified.
EOF
}

::cli::core::type::is_indexable::inline() {
    ::cli::core::type::is_modified::inline "$@" || (
        ::cli::core::type::is_builtin::inline "$@" \
        && ! ::cli::core::type::is_scaler::inline "$@"
    ) 
}

self_test() {
    ${CLI_COMMAND[@]} -- map_of string
    ${CLI_COMMAND[@]} -- map
    ${CLI_COMMAND[@]} -- array
    ! ${CLI_COMMAND[@]} -- boolean
}
