#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is modified.

Description
    Return true if the type is modified by:
    
        map_of

    otherwise false.

    A modified type is an associative array where the value is the name
    of a variable whose type is the element type of the modified type.
    For example a 'map_of map_of string' is a map whose values point to
    yet another map whose values point to strings.
EOF
}

::cli::core::type::is_modified::inline() {
    [[ "${1-}" =~ m ]]
}

self_test() {
    ${CLI_COMMAND[@]} -- m || cli::assert
    ! ${CLI_COMMAND[@]} -- A || cli::assert
}
