#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::source cli core type is-builtin
cli::source cli core type is-modified

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if type is user defined.

Description
    Return false if the type is:
    
        string
        integer
        boolean
        map
        array

    also return false if the type is modified:

        map_of

    otherwise, return true.
EOF
}

::cli::core::type::is_user_defined::inline() {   
    ! ::cli::core::type::is_modified::inline "$@" \
        && ! ::cli::core::type::is_builtin::inline "$1"
}

self_test() {
    ${CLI_COMMAND[@]} -- user_defined || cli::assert

    ! ${CLI_COMMAND[@]} -- boolean || cli::assert
    ! ${CLI_COMMAND[@]} -- string || cli::assert
    ! ${CLI_COMMAND[@]} -- integer || cli::assert
    ! ${CLI_COMMAND[@]} -- map || cli::assert
    ! ${CLI_COMMAND[@]} -- array || cli::assert
    ! ${CLI_COMMAND[@]} -- map_of string || cli::assert
    ! ${CLI_COMMAND[@]} -- string string || cli::assert
}
