#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli core type is-modified

help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return the type less one modifier or the type if self it is unmodified.

Description
    Return a type less one modifiers. For example, the unmodified type of
    
        map_of map_of string

    becomes 

        map_of string
EOF
}

::cli::core::type::unmodify::inline() {
    MAPFILE=()

    if ::cli::core::type::is_modified::inline "$@"; then
        shift
    fi

    MAPFILE=( "$@" )
}

self_test() {
    [[ "$(${CLI_COMMAND[@]} ---mapfile boolean)" == 'boolean' ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---mapfile map_of map_of boolean)" == $'map_of\nboolean' ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---mapfile string string)" == $'string\nstring' ]] || cli::assert
}
