#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Print the callstack.

Description
    Print the callstack where each record is composed of:

        frame file line

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    local i=0
    while read line frame file < <(caller $i); do
        printf '%-40s %-30s %s\n' $frame $file $line
        i=$(( i + 1 ))
    done
}

self_test() {
    set +e
    assert::fails "arg_message='failed' inline"
}

cli::load "$@"