#!/usr/bin/env bash
source $(cli loader)
cli::import_parent_group
cli::import cli_assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Print the callstack.

Description
    Print the callstack where each record is composed of:

        frame file line
EOF
}

inline() {
    local c=0
    local v=0

    echo $$

    set ${BASH_ARGC[@]:1}
    while read line subroutine file < <(caller $c); do
        
        local -a argv=()
        for (( i=0; i<$1; i++ )); do
            argv=( "${BASH_ARGV[${v}]}" "${argv[@]}" )
            v=$(( v + 1 ))
        done

        printf '[%s] %-50s %-30s:%s\n' \
            "${c}" \
            "${subroutine} ${argv[*]}" \
            "${file}" \
            "${line}"

        c=$(( c + 1 ))
        shift
    done | sed 's/^/  /'
}

self_test() {
    inline
}

cli::main "$@"