#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Print the callstack.

Description
    Print the callstack where each record is composed of:

        frame file line
EOF
}

cli::meta::declare() {
    :
}

::cli::bash::callstack::inline() {
    local frame=0
    local v=0

    # process id
    echo "${BASH_COMMAND} ($$ -> ${PPID})"

    # argument counts by frame
    set ${BASH_ARGC[@]:1} 0

    # walk stack
    while read line subroutine file < <(caller ${frame}); do
        
        local -a argv=()
        for (( i=0; i<${1-0}; i++ )); do
            argv=( "${BASH_ARGV[${v}]}" "${argv[@]}" )
            v=$(( v + 1 ))
        done

        printf '[%s] %-50s %s:%s\n' \
            "${frame}" \
            "${subroutine} ${argv[*]}" \
            "${file}" \
            "${line}"

        # next frame
        frame=$(( frame + 1 ))
        shift
    done | sed 's/^/  /'
}

self_test() {
    inline
}

cli::main "$@"