#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::help::sourceable
Command
    ${CLI_COMMAND[@]}
    
Summary
    Like 'declare -p' except only prints variables for which 'test -v' is true
    and with out failures for undefined variables.

Description
    Positional arguments $1, $2, etc are variable names that optionally end in '*'.

    All variables which match any of the positional arguments are printed like 
    they would be with 'declare -p. If a variable does not exist, nothing is printed.

Arguments
    --                      : The variables to emit.
EOF
    cat << EOF

Examples
    Emit the embedded variable 'MY_STRING'.
        declare MY_STRING='Hello World!'
        declare -p MY_STRING \
            | ${CLI_COMMAND[@]} -- MY_STRING

    Emit the embedded variables that start with 'MY_'.
        declare MY_STRING='Hello World!'
        declare -i MY_NUMBER=42
        declare -p MY_STRING MY_NUMBER \
            | ${CLI_COMMAND[@]} -- MY_* \

    Emit nothing.
        ${CLI_COMMAND[@]}

    Emit nothing.
        ${CLI_COMMAND[@]} -- ''
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::emit::inline() {
    for name in "$@"; do
        if [[ "${name}" =~ ^.*[*]$ ]]; then
            ::cli::bash::emit::inline $(eval "echo \${!${name}}")
        elif [[ -v "${name}" ]]; then
            declare -p "${name}"
        fi
    done
}

self_test() {
    echo \
        | ${CLI_COMMAND[@]} -- \
        | diff <(:) - || cli::assert

    echo \
        | ${CLI_COMMAND[@]} -- MY_NOT_DEFINED \
        | diff <(:) - || cli::assert

    echo \
        | ${CLI_COMMAND[@]} -- MY_NOT_DEFINED* \
        | diff <(:) - || cli::assert

    local -A MY_UNINIT_MAP
    local -a MY_UNINIT_ARRAY

    declare -p MY_UNINIT_MAP MY_UNINIT_ARRAY \
        | ${CLI_COMMAND[@]} -- MY_UNINIT_MAP MY_UNINIT_ARRAY \
        | diff <(:) - || cli::assert

    local MY_STRING='Hello world!'
    local -i MY_NUMBER=42
    local -A MY_MAP=([a]=0)
    local -a MY_ARRAY=(a)

    declare -p MY_STRING MY_NUMBER MY_MAP MY_ARRAY \
        | ${CLI_COMMAND[@]} -- 'MY_STRING' \
        | diff <(echo 'declare -- MY_STRING="Hello world!"') -

    declare -p MY_STRING MY_NUMBER MY_MAP MY_ARRAY \
        | ${CLI_COMMAND[@]} -- 'MY_*' \
        | diff <(cat <<-EOF
			declare -a MY_ARRAY=([0]="a")
			declare -i MY_NUMBER="42"
			declare -- MY_STRING="Hello world!"
			EOF
        ) -
}
