#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert
cli::import_inline cli bash callstack

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Print a message to stderr and exit with a non-zero code.

Arguments
    --exit-code -e          : The exit code to return. Default: 1.
    --message -m            : The error message message.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    : ${arg_exit_code=1}
    : ${arg_message='Unexpected general failure. You found a bug!'}

    echo "${arg_message}" >&2

    # {
        # ::cli::bash::callstack::inline
        # echo
        # echo ARGS:
        # for arg in ${!arg_*}; do
        #     declare -p ${arg} 
        # done
    # } | sed 's/^/    /' >&2

    exit ${arg_exit_code}
}

self_test() {
    set +e
    assert::fails "arg_message='failed' inline"
}

cli::load "$@"