#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group
cli::import cli-assert
cli::import_inline cli bash callstack

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Print a message to stderr and exit with a non-zero code.

Arguments
    --exit-code -e          : The exit code to return. Default: 1.
    --message -m            : The error message message.
EOF
}

cli::meta::declare() {
    cli::meta::add_optional 'exit-code' 1
    cli::meta::add_optional 'message'
}

::cli::bash::fail::inline() {
    : ${arg_exit_code=1}
    : ${arg_message='Unexpected general failure. You found a bug!'}

    echo "${arg_message}" >&2
    exit ${arg_exit_code}
}

self_test() {
    set +e
    assert::fails "arg_message='failed' inline" "failed"
}

cli::main "$@"