#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if the function is declared, otherwise false.

Arguments
    Argumetn $1 is the name of the function.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::is_function_declared::inline() {
    declare -F "${1-}" > /dev/null
}

self_test() {
    ::cli::bash::is_function_declared::inline self_test || cli::assert
    ! ::cli::bash::is_function_declared::inline missing || cli::assert
}
