#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Return true if the function is declared, otherwise false.

Arguments
    --name -n    [Required] : The name of the function.
EOF
    cat << EOF

Examples
    Test for the function 'inline'.
        ${CLI_COMMAND} --name inline
EOF
}

cli::meta::declare() {
    cli::meta::add_required 'name'
}

::cli::bash::is_function_declared::inline() {
    if declare -F "${1-}" > /dev/null; then 
        true
    else 
        false
    fi
}

main() {
    ::cli::bash::is_function_declared::inline "${arg_name}"
}

self_test() {
    ${CLI_COMMAND} --name inline
    assert::ok

    ${CLI_COMMAND} --name missing
    assert::failed
}

cli::main "$@"