#!/usr/bin/env bash
source $(cli loader)
cli::import_parent_group
cli::import cli_assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Return true if the function is declared, otherwise false.

Arguments
    --name -n    [Required] : The name of the function.
EOF
    cat << EOF

Examples
    Test for the function 'inline'.
        ${CLI_COMMAND} --name inline
EOF
}

import() {
    cli::meta::add_required 'name'
}

inline() {
    : ${arg_name?"Unexpected missing name of function."}

    if declare -F "${arg_name}" > /dev/null; then 
        true
    else 
        false
    fi
}

self_test() {
    ${CLI_COMMAND} --name inline
    assert::ok

    ${CLI_COMMAND} --name missing
    assert::failed
}

cli::main "$@"