#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Print a line to stdout composed of the arguments joined 
    using the first argument as the delimiter.

Description
    Argument $1 is a delimiter used to join the remaining arguments.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::join::inline() {
    local delimiter=${1?'Missing delimiter'}
    shift

    local -a segment=()
    while (( $# > 0 )); do
        segment+=( "$1" )
        shift
        if (( $# == 0 )); then break; fi
        segment+=( "${delimiter}" )
    done

    printf %s "${segment[@]}"
    echo
}

self_test() {
    diff <(::cli::bash::join::inline . a b c) - <<< 'a.b.c' || cli::assert
    diff <(::cli::bash::join::inline .) - <<< '' || cli::assert
}
