#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF | cli::help::sourceable
Command
    ${CLI_COMMAND[@]}
    
Summary
    Like 'declare -p' except only prints variables for which 'test -v' is true
    and with out failures for undefined variables.

Description
    Positional arguments $1, $2, etc are variable names that optionally end in '*'.

    All variables which match any of the positional arguments are printed like 
    they would be with 'declare -p. If a variable does not exist, nothing is printed.

Arguments
    --                      : The variables to emit.
EOF
    cat << EOF

Examples
    Emit the embedded variable 'MY_STRING'.
        declare MY_STRING='Hello World!'
        declare -p MY_STRING \
            | ${CLI_COMMAND[@]} -- MY_STRING

    Emit the embedded variables that start with 'MY_'.
        declare MY_STRING='Hello World!'
        declare -i MY_NUMBER=42
        declare -p MY_STRING MY_NUMBER \
            | ${CLI_COMMAND[@]} -- MY_* \

    Emit nothing.
        ${CLI_COMMAND[@]}

    Emit nothing.
        ${CLI_COMMAND[@]} -- ''
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::list::inline() {
    MAPFILE=()

    for name in "$@"; do
        if [[ "${name}" =~ ^.*[*]$ ]]; then
            for match in $(eval "echo \${!${name}}"); do
                # do not recurse! test -v arr=() is false
                MAPFILE+=( "${match}" )
            done
        elif [[ -v "${name}" ]]; then
            MAPFILE+=( "${name}" )
        else
            # declare -a arr=()
            for match in $(eval "echo \${!${name}*}"); do
                if [[ "${match}" == "${name}" ]]; then
                    MAPFILE+=( "${name}" )
                fi
            done
        fi
    done
}


self_test() {
    ${CLI_COMMAND[@]} -- \
        | diff <(:) - || cli::assert

    ${CLI_COMMAND[@]} -- MY_NOT_DEFINED \
        | diff <(:) - || cli::assert

    ${CLI_COMMAND[@]} -- MY_NOT_DEFINED* \
        | diff <(:) - || cli::assert

    local -A MY_UNINIT_MAP
    local -a MY_UNINIT_ARRAY

    ${CLI_COMMAND[@]} -- MY_UNINIT_MAP MY_UNINIT_ARRAY \
        | diff <(:) - || cli::assert

    local MY_STRING='Hello world!'
    local MY_EMPTY_STRING=""
    local MY_DECL_STRING

    local -a MY_ARRAY=(a)
    local -a MY_EMPTY_ARRAY=()
    local -a MY_DECL_ARRAY

    local -A MY_MAP=([a]=0)
    local -A MY_EMPTY_MAP=()
    local -A MY_DECL_MAP

    local -i MY_NUMBER=42
    local -i MY_DECL_NUMBER

    ${CLI_COMMAND[@]} -- 'MY_STRING' \
        | diff <(echo 'declare -- MY_STRING="Hello world!"') -

    ${CLI_COMMAND[@]} -- 'MY_DECL_ARRAY MY_DECL_MAP MY_DECL_STRING MY_DECL_NUMBER' \
        | diff <(:) - || cli::assert

    ${CLI_COMMAND[@]} -- 'MY_*' \
        | sort -k3 \
        | diff <(cat <<-EOF
			declare -a MY_ARRAY=([0]="a")
			declare -a MY_EMPTY_ARRAY=()
			declare -A MY_EMPTY_MAP=()
			declare -- MY_EMPTY_STRING=""
			declare -A MY_MAP=([a]="0" )
			declare -i MY_NUMBER="42"
			declare -- MY_STRING="Hello world!"
			EOF
        ) -

    ${CLI_COMMAND[@]} -- MY_ARRAY MY_EMPTY_ARRAY MY_EMPTY_MAP MY_EMPTY_STRING MY_MAP MY_NUMBER MY_STRING \
        | sort -k3 \
        | diff <(cat <<-EOF
			declare -a MY_ARRAY=([0]="a")
			declare -a MY_EMPTY_ARRAY=()
			declare -A MY_EMPTY_MAP=()
			declare -- MY_EMPTY_STRING=""
			declare -A MY_MAP=([a]="0" )
			declare -i MY_NUMBER="42"
			declare -- MY_STRING="Hello world!"
			EOF
        ) -

}
