#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Use echo to copy arguments to stderr.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::log::inline() {
    echo "$@" >&2
}

self_test() {
    log() { ::cli::bash::log::inline "$@"; }

    diff <(log a b c 2> /dev/null; echo) - <<< '' || cli::assert
    diff <(log a b c 2>&1) - <<< 'a b c' || cli::assert
}
