#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::sourceable | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Emit a variable declaration.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    :
}

self_test() {
    :
}
