#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Returns 0.

Description
    Returns the first positonal argument. Default is 0.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::bash::return::inline() {
    return ${1-0}
}

self_test() {
    ::cli::bash::return::inline || cli::assert
    ! ::cli::bash::return::inline 1 || cli::assert
}
