#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert

help() {
    cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Test if a set of functions is declared.

Arguments
    --                      : Name of functions.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.
EOF
}

inline() {
    declare -F "$@" > /dev/null
}

self_test() {
    set +e

    ${CLI_COMMAND} -- inline self_test
    assert::ok 'self_test'

    ${CLI_COMMAND} -- not_declared
    assert::failed 'not_declared'

    ${CLI_COMMAND} ---emit | source /dev/stdin
    ::cli::util::is_declared::inline inline self_test
    assert::ok 'inline self_test'

    ${CLI_COMMAND} ---emit | source /dev/stdin
    ::cli::util::is_declared::inline not_declared
    assert::failed 'inline not_declared'
}

cli::load "$@"