#!/usr/bin/env bash
source $(cli loader)

help() {
cat << EOF
Command
    ${CLI_PATH}
    
Summary
    Read stdin into an associative array.

Description
    Reads an even number of lines from a file to populate an associative
    array. Even lines are keys and odd lines are values. The associative
    array must be declared before calling readmap and passed as argument
    'name'. As such, this function can only be used inline. 

Arguments
    --name       [Required] : Name of associative shell variable.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Source readmap and load 'key' 'value' into 'map'.
        ${CLI_PATH} ---inline readmap | source /dev/stdin; \\
        declare -A map; \\
        arg_name=map readmap < <(echo key; echo value)
EOF
}

main() {
    declare -n ref=${arg_name}

    while read -r key; do
        read -r value
        ref+=( [$key]="$value" )
    done
}

cli::load "$@"