#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Read stdin into an associative array.

Description
    Declare a set represented an associative where each value is 
    'true' and each key is read from stdin.

Arguments
    --name -n               : The name of the associative array. Default: RESULT.
EOF
    cat << EOF

Examples
    Create the set { 'a' 'b' 'c' }.
        ${CLI_COMMAND[@]} -emit <<< $'a\n\b\nc'
EOF
}

cli::meta::declare() {
    cli::meta::add_optional 'name' 'RESULT'
}

inline() {
    : ${arg_name=RESULT}

    declare -n ref=${arg_name}

    while read -r; do
        eval "ref+=( [$REPLY]=true )"
    done
}

main() {
    declare -A ${arg_name}
    inline
    declare -p ${arg_name}
}

self_test() {
    # cat /dev/null \
    # | ${CLI_COMMAND[@]} --name set \
    # | assert::pipe_eq \
    #     'declare -A set'

    # ${CLI_COMMAND[@]} --name set <<< $'a' \
    # | assert::pipe_eq \
    #     'declare -A set=([a]="true" )'

    printf '%q\n' $'\n' \
    | ${CLI_COMMAND[@]} --name set
    # | assert::pipe_eq \
    #     'declare -A set=([a]="true" )'
    
    exit

    ${CLI_COMMAND[@]} --name set <<< $'a\nb' \
    | assert::pipe_eq \
        'declare -A set=([b]="true" [a]="true" )'

    declare -A RESULT
    ${CLI_COMMAND[@]} ---emit | source /dev/stdin
    ::cli::util::readset::inline <<< $'a'
    assert::pipe_eq < <(declare -p RESULT) \
        'declare -A RESULT=([a]="true" )'
}
