#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash string literal 

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
EOF
}

::cli::bash::emit::initializer::string::inline() {
    [[ ${1:-} ]] || cli::assert 'Missing string variable name.'

    local -n REF=${1-}
    ::cli::bash::string::literal::inline "${REF}"
    echo -n "${REPLY}"
}

self_test() {
    local VALUE='a b c'
    diff <( ${CLI_COMMAND[@]} -- VALUE; echo ) - <<< $'"a b c"'
}
