#!/usr/bin/env CLI_TOOL=cli bash-cli-part

cli::sample::recurse::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]} 

Summary    
    Sample command to test Domain Specific Language.

Arguments
    --depth                     : Initial depth. Default: 0.
    --max                       : Max depth. Default: 2.
EOF
}

cli::sample::recurse::main() {
    echo ${ARG_DEPTH}
    if (( ${ARG_DEPTH} == ${ARG_MAX} )); then
        return
    fi

    ${CLI_COMMAND[@]} --depth $(( ${ARG_DEPTH} + 1 )) --max ${ARG_MAX}
    echo ${ARG_DEPTH}
}

cli::sample::recurse::self_test() {
    local CACHE="$(${CLI_COMMAND[@]} ---cache)/meta.sh"
    if [[ -f "${CACHE}" ]]; then
        rm "${CACHE}"
    fi

    diff <(${CLI_COMMAND[@]}) - <<-EOF
		0
		1
		2
		1
		0
		EOF
}   
