#!/usr/bin/env CLI_TOOL=cli bash-cli-part

cli::sample::simplest::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]} 

Summary    
    Sample command to test Domain Specific Language.
EOF
}

cli::sample::simplest::main() {
    :    
}

cli::sample::simplest::self_test() {
    return
}   
