#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli shim which

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    ...
EOF
}

::cli::shim::main::inline() {

    # CLI_NAME
    [[ "${CLI_NAME}" =~ ${CLI_REGEX_NAME} ]] \
        || cli::assert "Shim '${CLI_NAME}' does not match regex '${CLI_REGEX_NAME}'."

    # CLI_COMMAND
    local -a CLI_COMMAND=( "${CLI_NAME}" )
    while [[ "${1-}" =~ ${CLI_REGEX_NAME} ]]; do
        CLI_COMMAND+=( "$1" )
        shift
    done

    # CLI_SOURCE
    ::cli::shim::which::inline "${CLI_COMMAND[@]}" \
        || cli::assert "Failed to find shim for '${CLI_COMMAND[@]}'."
    local CLI_SOURCE="${REPLY}"

    cli::loader::main "$@"
}

self_test() {
    cli::temp::dir
    local DIR="${REPLY}"
    local FOO_SRC_DIR="${DIR}/src"
    local FOO_BAR="${DIR}/src/bar"
    
    # emit foo shim
    declare -rg CLI_SHIM_ROOT_DIR_FOO="${FOO_SRC_DIR}"
    foo() { 
        local CLI_NAME="${FUNCNAME}"
        ::cli::shim::main::inline "$@"
    }

    # shim /src
    mkdir "${FOO_SRC_DIR}"

    # emit bar command
    cat <<-EOF > "${FOO_BAR}"
		::foo::bar::inline() { echo "\$@"; }
		EOF
    chmod a+x "${FOO_BAR}"

    # foo
    diff <(foo bar --- a0 a1 a2) - <<< 'a0 a1 a2' || cli::assert
}
