#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli shim source

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Resolve a cli command to a path.

Arguments
    Argument \$1 is the name of the cli. If the shim for \$1 is not found, 
    the call fails, otherwise succeeds.

    Arguments \$2 and greater are the groups leading to the command. They are
    joined together with forward shashes and that string is joined to the root 
    directory of the commands for the cli again with a forward slash and that 
    string is then assigned to REPLY.
EOF
}

::cli::shim::which::inline() {
    local NAME="$1"
    shift

    ::cli::shim::source::inline "${NAME}" \
        || return 1

    local -n SHIM_ROOT_DIR_REF="CLI_SHIM_ROOT_DIR_${NAME^^}"
    [[ "${SHIM_ROOT_DIR_REF-}" ]] || cli::assert

    local IFS=/
    REPLY="${SHIM_ROOT_DIR_REF}/$*"
}

self_test() {
    which() {
        ::cli::shim::which::inline "$@" || return 1
        echo "${REPLY-}"
    }

    diff <(echo $0) <(which cli shim which) || cli::assert

    cli::temp::dir 
    local DIR="${REPLY}"

    local FOO_SHIM="${DIR}/foo"
    local FOO_SRC_DIR="${DIR}/src"
    local FOO_BAR="${DIR}/src/bar"
    
    # emit foo shim
    cat <<-EOF > "${FOO_SHIM}"
		#!/usr/bin/env bash-cli-shim
        declare -rg CLI_SHIM_ROOT_DIR_FOO="\${FOO_SRC_DIR}"
		foo() { cli::assert; }
		EOF
    chmod a+x "${FOO_SHIM}"

    ! which foo bar || cli::assert

    # update PATH
    PATH+=":${DIR}"

    # which foo
    diff <(which foo bar) - <<< "${FOO_BAR}" || cli::assert
}
