#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash variable initialize
cli::import cli core variable parse
cli::import cli core type is-scaler
cli::import cli core type is-builtin
cli::import cli core type is-modified
cli::import cli core type is-user-defined

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Declare and initialize a bash variable or variables for a given type.

Description
    Declares and initializes a global bash variable or variables depending on 
    the provided type.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

cli::core::variable::declare::main() {
    ::cli::core::variable::declare::inline "$@"

    set "${MAPFILE[@]}"
    while (( $# > 0 )); do
        cli::dump "$1" "$1_*"
        shift
    done
}

::cli::core::variable::declare::inline() {
    local -a names=()

    while (( $# > 0 )); do

        ::cli::core::variable::parse::inline "$@"

        local name=${REPLY}
        local -n ref="${name}"
        shift

        local -a type=( ${MAPFILE[@]} )
        shift ${#MAPFILE[@]}

        names+=( "${name}" )

        if ::cli::core::type::is_modified::inline "${type[@]}"; then
            type=( map )
        fi

        if ::cli::core::type::is_builtin::inline "${type[@]}"; then
            ::cli::bash::variable::initialize::inline "${type[@]}" "${name}"
        else
            ::cli::core::type::is_user_defined::inline "${type[@]}" \
                || cli::assert

            # bgen optimization
            # local bgen=${CLI_BGEN_DECLARE[CLI_TYPE_${ARG_TYPE^^}]-}
            # if [[ -n ${bgen} ]]; then
            #     ${bgen} ${ARG_NAME}
            #     return
            # fi
            # echo "--- MISSING BGEN FOR CLI_TYPE_${ARG_TYPE^^} ---" > /dev/stderr

            local -n "type_ref=CLI_TYPE_${type[@]^^}"

            # layout fields
            local field
            for field in "${!type_ref[@]}"; do
                local "field_type=${type_ref[$field]}"

                # recursively declare fields
                ::cli::core::variable::declare::inline \
                    ${field_type} \
                    "${name}_${field^^}"
            done
        fi
    done

    MAPFILE=( "${names[@]}" )
}

self_test() {
    diff <(${CLI_COMMAND[@]} -- string VAR) - <<< 'declare -- VAR=""' || cli::assert
    diff <(${CLI_COMMAND[@]} -- integer VAR) - <<< 'declare -i VAR="0"' || cli::assert
    diff <(${CLI_COMMAND[@]} -- boolean VAR) - <<< 'declare -- VAR="false"' || cli::assert
    diff <(${CLI_COMMAND[@]} -- array VAR) - <<< 'declare -a VAR=()' || cli::assert
    diff <(${CLI_COMMAND[@]} -- map VAR) - <<< 'declare -A VAR=()' || cli::assert
    diff <(${CLI_COMMAND[@]} -- map_of integer VAR) - <<< 'declare -A VAR=()' || cli::assert

    # udt
    declare -A CLI_TYPE_VERSION=(
        [major]='integer'
        [minor]='integer'
    )

    # kitchen sink
    declare -A CLI_TYPE_UDT=(
        [my_string]='string'
        [my_integer]='integer'
        [my_boolean]='boolean'
        [my_map]='map'
        [my_array]='array'
        [my_map_of_string]='map_of string'
        [my_version]='version'
        [my_map_of_version]='map_of version'
    )

    ${CLI_COMMAND[@]} --- udt VAR \
        | sort -k3 \
        | diff <(cat <<-EOF
			declare -a VAR_MY_ARRAY=()
			declare -- VAR_MY_BOOLEAN="false"
			declare -i VAR_MY_INTEGER="0"
			declare -A VAR_MY_MAP=()
			declare -A VAR_MY_MAP_OF_STRING=()
			declare -A VAR_MY_MAP_OF_VERSION=()
			declare -- VAR_MY_STRING=""
			declare -i VAR_MY_VERSION_MAJOR="0"
			declare -i VAR_MY_VERSION_MINOR="0"
			EOF
        ) -

    ${CLI_COMMAND[@]} --- \
        string MY_STRING_0 \
        string MY_STRING_1 \
        | sort -k3 \
        | diff <(cat <<-EOF
			declare -- MY_STRING_0=""
			declare -- MY_STRING_1=""
			EOF
        ) -
}
