#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash emit block paren 
cli::import cli bash emit expression key 
cli::import cli bash emit literal string 

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
EOF
}

::cli::bash::emit::literal::array::inline() {
    local NAME="$1"
    local -n REF=${1?'Missing map variable name.'}

    local INDEX
    for (( INDEX=0; INDEX < ${#REF[@]}; INDEX++ )); do
        local VALUE="${REF[$INDEX]}"

        ::cli::bash::emit::expression::key::inline ${INDEX}
        echo -n '='
        ::cli::bash::emit::literal::string::inline VALUE
        
        echo
    done | ::cli::bash::emit::block::paren::inline

    # local -n REF=${1?'Missing array variable name.'}
    # ::cli::bash::array::literal::inline "${REF[@]}"
    # echo -n "${REPLY}"
}

self_test() {
    local ARR=(a)
    diff <( ${CLI_COMMAND[@]} -- ARR; echo ) - <<< $'(\n    [0]="a"\n)'
}
