#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash key literal 

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
EOF
}

::cli::bash::emit::literal::key::inline() {
    ::cli::bash::key::literal::inline "$@"
    echo -n "${REPLY}"
}

self_test() {
    diff <( ${CLI_COMMAND[@]} -- a; echo ) - <<< $'a'
    diff <( ${CLI_COMMAND[@]} -- '$'; echo ) - <<< '"\$"'
}
