#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Emit a function that defines 'initialize' for a cli.

Description
    Emit a function that defines initialize for a cli unless initialize is
    already defined.

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Exmaples
    Emit 'cli::find::define_initialize'
        cli find | cli emit define-initialize
EOF
}

main() (
    ${arg_cli} '---initialize' \
        | read; cat "${REPLY}" \
        | { \
            # if there is no generated initialize function, then emit nothing
            if ! read; then return; fi

            cat <(echo ${REPLY}) - \
                | emit::file \
                | emit::function "$(cli::emit::library_name ${arg_cli} 'define_initialize')"
        }
)

cli::load "$@"