#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Emit a function containing a library's source.

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
EOF
}

main() (
    ${arg_cli} \
        | emit::function "$(cli::emit::library_name "${arg_cli}" 'source')"
)

cli::main "$@"