#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Emit a function containing a library's source.

Arguments
    --cli -c     [Required] : Name of the cli.
EOF
}

main() (
    ${arg_cli} \
        | emit::function "$(cli::emit::library_name "${arg_cli}" 'source')"
)

cli::main "$@"