#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Emit a function containing a library's source.

Arguments
    --cli -c     [Required] : Name of the cli.
EOF
}

main() (
    ${arg_cli} \
        | emit::function "$(cli::emit::library_name "${arg_cli}" 'source')"
)

cli::main "$@"