#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}

Arguments
    --cli -c     [Required] : Name of the cli.
EOF
}

main() (
    ${arg_cli} '---print' \
        | emit::file \
        | emit::subproc "$(cli::emit::library_name ${arg_cli})"; \
)

cli::main "$@"