#!/usr/bin/env CLI_NAME=cli bash-cli-part

cli::emit::packed::subproc::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Arguments
    --cli -c     [Required] : Name of the cli.
EOF
}

main() (
    ${arg_cli} '---print' \
        | emit::file \
        | emit::subshell "$(cli::emit::library_name ${arg_cli})"; \
)

cli::main "$@"
