#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF
Command
    ${CLI_PATH}

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Exmpales
EOF
}

main() (
    ${arg_cli} '---print' \
        | emit::file \
        | emit::subproc "$(cli::emit::library_name ${arg_cli})"; \
)

cli::load "$@"