#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Declare a bash variable or variables for a given type. 

Description
    Argument $1 is the type and $2 is the name of the variable and so forth
    for $3 and $4 etc. Names must be valid bash names and will be declared
    globally.

    Valid types are

        string
        boolean
        integer
        map
        array

    Variable are _not_ initialized. So if 'set -u' is enabled, then dereferencing
    a variable will result in an 'unbound variable' error. 
EOF
}

cli::bash::variable::declare::main() {
    ::cli::bash::variable::declare::inline "$@" || return 1

    while (( $# > 0 )); do
        shift
        declare -p $1
        shift
    done
}

::cli::bash::variable::declare::inline() {

    while (( $# > 0 )); do

        local type=${1?'Missing variable type.'}
        shift

        local name=${1?'Missing variable name.'}
        shift

        # initialize declare flags
        local flags=g
        case ${type} in
            'integer') flags+=i ;;
            'array') flags+=a ;;
            'map') flags+=A ;;
            'string') ;;
            *) cli::assert "Unknown bash type '${type}'."
        esac

        # declare the bash variable
        declare -${flags} ${name}
    done
}

self_test() {
    [[ "$(${CLI_COMMAND[@]} -- string VAR)" == "declare -- VAR" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} -- integer VAR)" == "declare -i VAR" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} -- array VAR)" == "declare -a VAR" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} -- map VAR)" == "declare -A VAR" ]] || cli::assert

    diff <( ${CLI_COMMAND[@]} -- \
        string MY_STRING \
        map MY_MAP \
    ) - <<-EOF || cli::assert
		declare -- MY_STRING
		declare -A MY_MAP
		EOF
}
