#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash emit literal key

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
EOF
}

::cli::bash::emit::expression::key::inline() {
    echo -n "["
    ::cli::bash::emit::literal::key::inline "$1"
    echo -n "]"
}

self_test() {
    diff <( ${CLI_COMMAND[@]} -- key; echo ) - <<< $'[key]'
}
