#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import_inline cli subshell dump
cli::import_inline cli bash stack trace

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Prints "ASSERT FAILED:" followed by a IFS join of the arguments
    to stderr stream before exiting with code 1.

Examples
    Test a condition
        [[ ${foo} == 'bar' ]] || ${CLI_COMMAND} -- 'Foo does not equal bar.'
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::subshell::assert::inline "$@"
}

::cli::subshell::assert::inline() {
    if (( $# == 0 )); then 
        set 'Condition failed'
    fi

    {
        echo "ASSERT FAILED:" "$*"
        ::cli::bash::stack::trace::inline \
            | sed 's/^/  /'
    } | ::cli::subshell::dump::inline
}

self_test() {
    cli::source cli-assert

    diff <(main 'Bad juju!' 2>&1; cli::assert) - << EOF || cli::assert
ASSERT FAILED: Bad juju!
  main "Bad juju!"                                   ${CLI_ROOT_DIR}subshell/assert:27
  self_test --self-test                              ${CLI_ROOT_DIR}subshell/assert:44
EOF

    diff <(main 2>&1; cli::assert) - << EOF || cli::assert
ASSERT FAILED: Condition failed
  main                                               ${CLI_ROOT_DIR}subshell/assert:27
  self_test --self-test                              ${CLI_ROOT_DIR}subshell/assert:50
EOF
}

cli::main "$@"