#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import_inline cli subshell dump

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Copies an IFS join of the arguments to stderr stream before exiting 
    with code 1.

Examples
    Test a condition
        [[ \${foo} == 'bar' ]] || ${CLI_COMMAND} -- 'Foo does not equal bar.'
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::subshell::fail::inline "$@"
}

::cli::subshell::fail::inline() {
    echo "$*" \
        | ::cli::subshell::dump::inline
}

self_test() {
    diff <(main 'Bad juju!' 2>&1; cli::assert) <( echo 'Bad juju!' ) \
        || cli::assert
}

cli::main "$@"

