#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return true if the variable is declared, false otherwise.

Description
    Argument \$1 is the name of the variable. 
EOF
}

::cli::bash::variable::is_declared::inline() {
    declare -p $1 2>/dev/null >&2
}

self_test() {
    ! ${CLI_COMMAND[@]} -- CLI_TYPE_VERSION || cli::assert

    local -A CLI_TYPE_VERSION=(
        [major]='integer'
        [minor]='integer'
    )

    ${CLI_COMMAND[@]} -- CLI_TYPE_VERSION || cli::assert
}
