#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import_inline cli process parent

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Set BASHPPID to the parent process id of the subshell. 

Description
    If there command is not executing in a subshell the call fails
    by returning a non zero value.

    If BASHPPID is already set, then it will be overwritten.
EOF
}

main() {
    cli::subshell::parent "$@"
    declare -p BASHPID
}

cli::subshell::parent() {
    (( $$ != $BASHPID )) || return 1
    cli::process::parent
    declare -gi BASHPPID=${REPLY}
}

self_test() {
    ! cli::subshell::parent || cli::assert

    ( 
        cli::subshell::parent || cli::assert
        [[ "${BASHPPID}" == "$$" ]] || cli::assert "${BASHPPID}" == "$$"
    )
}

cli::main "$@"