#!/usr/bin/env CLI_NAME=cli bash-cli-part

cli::emit::packed::reflection::is_command::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Emit predicate 'is_command' for a cli.

Arguments
    --name -n    [Required] : Name of the function. 
                              Default: cli::shim::is_command.
EOF
    cat << EOF

Examples
    Emit a predicate that test if a path is a command.
        cli find --cli cli --type c \
            | ${CLI_COMMAND[@]}
EOF
}

main() (
    while read; do cli::emit::library_name ${REPLY}; done \
        | emit::function_contains "${arg_name}"
)

cli::main "$@"
