#!/usr/bin/env CLI_NAME=cli bash-cli-part

cli::emit::packed::reflection::list::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]} 
    
Summary
    Emit function 'list' for a cli.
    
Description
    Emit a function that lists commands and groups of a group 
    encoded as a library name.

Arguments
    --cli -c     [Required] : Name of the cli.
EOF
    cat << EOF

Examples
    ${CLI_COMMAND[@]} --cli cli
EOF
}

list_cases() {
    $@ \
        | awk '{print "echo", $1, $2}' \
        | emit::case "$(cli::emit::library_name $@)"

    $@ \
        | awk '$1 == "g" {print $2}' \
        | while read; do list_cases "$@" "${REPLY}"; done
}

main() (
    list_cases "${arg_cli}" \
        | emit::case_statement '$@' \
        | emit::function 'cli::shim::list'
)

cli::main "$@"
