#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import_inline cli subshell temp clean

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Exit trap that deletes temporary files and directories created by this subprocess.
EOF
}

cli::meta::declare() {
    :
}

main() {
    ::cli::subshell::trap::exit::inline "$@"
}

::cli::subshell::trap::exit::inline() {
    ::cli::subshell::temp::clean::inline
}

self_test() {
    :
}
