#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli bash array pop

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return positional arguments less the last one in MAPFILE.
EOF
}

::cli::bash::array::foo::inline() {
    (( $# > 0 )) || cli::assert 'Stack empty.'
    MAPFILE=( ${@:1:$((${#@}-1))} )
}

self_test() {
    declare -f ::cli::bash::array::pop::inline
    ::cli::bash::array::pop::inline ---mapfile a
}
