#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Return positional arguments less the last one in MAPFILE.
EOF
}

::cli::bash::array::pop::inline() {
    (( $# > 0 )) || cli::assert 'Stack empty.'
    MAPFILE=( ${@:1:$((${#@}-1))} )
}

self_test() {
    diff <(${CLI_COMMAND[@]} ---mapfile a) - < /dev/null || cli::assert
    diff <(${CLI_COMMAND[@]} ---mapfile a b) - <<< 'a' || cli::assert
}
