#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Set REPLY to the group id of $1. 

Description
    By default $1 is the process id of the subprocess. 
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::proc::parent::inline "$@"
    declare -p REPLY
}

::cli::process::parent::inline() {
    local PID=${1-${BASHPID}}
    read < <(ps -p $$ -o pgid=)
}

self_test() {
    :
}
