#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Description
    Read command help tokens from stdin and emit productions to stdout 
    one per line in the form:

        key production_id production_name [identifier]

    The productions harvested from a command's help are designed to
    be joined with productions harvested from the parsing of the 
    command line arguments to simplify validating the arguments
    against the help metadata. The join is constructed by
    mergeing the streams of production tokens and sorting them by 
    'key' and then by 'production_id'. In this way, if PRODUCTION_NAME
    appears before PRODUCTION_ARG_NAME, then the argument is expected,
    otherwise it is unexpected.

Arguments
    --               : The file to report is being parsed if an error occurs.
EOF
    cat << EOF

Examples
    Parse the sample help.
        cli dsl help sample -h | cli dsl help tokenize | cli dsl help parse
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

yield() {
    echo "${arg_group}" "${arg_name}" "${CLI_DSL_PRODUCTION[$1]}" "${2-}"
}

error() {
    arg_name='.'
    # callstack=$(cli::log_callstack)
    yield ${CLI_DSL_PRODUCTION_ERROR} "$1"
    exit
}

bad_token() {
    local message
    local -a expected
    
    for i in "$@"; do
        expected+=( ${CLI_DSL_TOKEN[$i]} )
    done
    
    message="Error parsing help of '${ARG_FILE:="<unknown>"}' at
         line ${line}, word ${word}: Expected token in { ${expected[@]} }, 
        but got ${token_name}, identifier='${identifier}'"

    error "${message}"
}

assert_token_is() {
    for expected_token in "$@"; do
        if (( token == expected_token )); then
            return

        elif (( token == CLI_DSL_TOKEN_ERROR )); then
            error "${identifier}"
        fi
    done

    bad_token $@
}

read_token() {
    read token_name line word identifier
    token="CLI_DSL_TOKEN_${token_name}"
    token=${!token}

    if (( $# > 0 )); then
        assert_token_is "$@"
    fi
}

main() {
    local ARG_FILE=${1-'UNKNOWN'}

    declare line
    declare word
    declare token
    declare token_name
    declare identifier
    declare arg_group
    declare arg_name

    START() {
        ARGUMENTS_GROUP
    }

    ARGUMENTS_GROUP() {
        read_token

        while (( token != CLI_DSL_TOKEN_EOF )); do
            assert_token_is ${CLI_DSL_TOKEN_ARGUMENTS}
            arg_name='.'
            arg_group=${identifier:='*'}
            yield ${CLI_DSL_PRODUCTION_ARGUMENTS} "${identifier}"
            ARGUMENTS
        done
    }

    ARGUMENTS() {
        read_token

        while true; do
            if (( token == CLI_DSL_TOKEN_DASHDASH )); then
                yield ${CLI_DSL_PRODUCTION_ANYARGS}
                read_token
            elif (( token == CLI_DSL_TOKEN_NAME )); then
                ARGUMENT
            else
                break
            fi
        done
    }

    ARGUMENT() {
        assert_token_is ${CLI_DSL_TOKEN_NAME}
    
        arg_name=${identifier}
        yield ${CLI_DSL_PRODUCTION_NAME} "${identifier}"
        read_token

        if (( token == CLI_DSL_TOKEN_ALIAS )); then ALIAS; fi
        if (( token == CLI_DSL_TOKEN_REQUIRED )); then REQUIRED; fi

        if (( token == CLI_DSL_TOKEN_FLAG )); then FLAG;
        elif (( token == CLI_DSL_TOKEN_LIST )); then LIST;
        elif (( token == CLI_DSL_TOKEN_PROPERTIES )); then PROPERTIES; 
        else 
            yield ${CLI_DSL_PRODUCTION_TYPE} 'string'
        fi

        ATTRIBUES
    }

    ATTRIBUES() {
        while true; do
            if (( token == CLI_DSL_TOKEN_DEFAULT )); then
                DEFAULT
            elif (( token == CLI_DSL_TOKEN_REGEX )); then
                REGEX
            elif (( token == CLI_DSL_TOKEN_ALLOWED_VALUES )); then
                ALLOWED_VALUES
            else
                break
            fi
       done
    }

    ALIAS() {
        yield ${CLI_DSL_PRODUCTION_ALIAS} "${identifier}"
        read_token
    }

    REQUIRED() {
        yield ${CLI_DSL_PRODUCTION_REQUIRED}
        read_token
    }

    FLAG() {
        yield ${CLI_DSL_PRODUCTION_FLAG}
        yield ${CLI_DSL_PRODUCTION_TYPE} 'boolean'
        read_token
    }

    LIST() {
        yield ${CLI_DSL_PRODUCTION_TYPE} 'array'
        read_token
    }

    PROPERTIES() {
        yield ${CLI_DSL_PRODUCTION_TYPE} 'map'
        read_token
    }

    REGEX() {
        read_token ${CLI_DSL_TOKEN_VALUE_PERIOD}
        yield ${CLI_DSL_PRODUCTION_REGEX} "${identifier}"
        read_token
    }

    DEFAULT() {
        read_token ${CLI_DSL_TOKEN_VALUE_PERIOD}
        yield ${CLI_DSL_PRODUCTION_DEFAULT} "${identifier}"
        read_token
    }

    ALLOWED_VALUES() {
        yield ${CLI_DSL_PRODUCTION_ALLOWED} "${identifier}"

        while true; do
            read_token $CLI_DSL_TOKEN_VALUE_COMMA $CLI_DSL_TOKEN_VALUE_PERIOD

            if (( token == CLI_DSL_TOKEN_VALUE_COMMA )); then
                yield ${CLI_DSL_PRODUCTION_ALLOWED_VALUE} "${identifier}"

            elif (( token == CLI_DSL_TOKEN_VALUE_PERIOD )); then
                yield ${CLI_DSL_PRODUCTION_ALLOWED_VALUE} "${identifier}"
                yield ${CLI_DSL_PRODUCTION_ALLOWED_END}
                read_token
                break
            fi
        done
    }

    START
}

self_test() {
    cli dsl sample -h \
        | cli dsl tokenize \
        | cli dsl parse \
        | assert::pipe_eq \
            'id . ARGUMENTS id' \
            'id id NAME id' \
            'id id ALIAS i' \
            'id id TYPE string' \
            'name . ARGUMENTS name' \
            'name name NAME name' \
            'name name TYPE string' \
            'name namespace NAME namespace' \
            'name namespace TYPE string' \
            '* . ARGUMENTS *' \
            '* run-as NAME run-as' \
            '* run-as TYPE string' \
            '* fruit NAME fruit' \
            '* fruit ALIAS f' \
            '* fruit TYPE string' \
            '* fruit DEFAULT banana' \
            '* fruit ALLOWED ' \
            '* fruit ALLOWED_VALUE orange' \
            '* fruit ALLOWED_VALUE banana' \
            '* fruit ALLOWED_END ' \
            '* header NAME header' \
            '* header REQUIRED ' \
            '* header TYPE string' \
            '* header REGEX ^[A-Z][A-Za-z0-9_]*$' \
            '* dump NAME dump' \
            '* dump ALIAS d' \
            '* dump FLAG ' \
            '* dump TYPE boolean' \
            '* my-list NAME my-list' \
            '* my-list ALIAS l' \
            '* my-list TYPE array' \
            '* my-props NAME my-props' \
            '* my-props ALIAS p' \
            '* my-props TYPE map' \
            '* my-props ANYARGS ' \
            '* . ARGUMENTS *' \
            '* help NAME help' \
            '* help ALIAS h' \
            '* help FLAG ' \
            '* help TYPE boolean' \
            '* self-test NAME self-test' \
            '* self-test FLAG ' \
            '* self-test TYPE boolean'
}
