#!/usr/bin/env bash
source $(cli loader)

help() {
    cat << EOF
Command
    ${CLI_PATH} 

Summary    
    Sample command to test Domain Specific Language.

Arguments
    --run-as                    : Run as the specified user.
                                    --ignore-me -i.
    --fruit                     : Run elevated. Default: banana. Allowed
                                    values: orange, banana. Stuff. Allowed ish.
    --header         [Required] : Header.
    --display-args       [Flag] : Display args.
    --                          : Arbitrary arguments.

Global Arguments
    --help -h            [Flag] : Show this message and exit.
    --self-test          [Flag] : Runs a self test.

Examples
    --ignore-me -i   [Required] : Default 10.
EOF
}

main() {
    echo "${arg_header}"
    echo "whoami=$(whoami)"
    if [[ "${arg_display_args}" == 'true' ]]; then
        echo "\$0 -- $0"
        echo "\$@ -- $@"
        declare -p | grep arg_
    fi
    # while read; do echo "${REPLY}"; done
}

self_test() {
    return
}   

cli::load "$@"