#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import_inline cli stderr dump
cli::import_inline cli bash stack trace

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}
    
Summary
    Copies "ASSERT FAILED:" followed by a IFS join of the arguments or, if
    there are no aguments, than 'Condition failed' to stderr stream before 
    issuing a CTRL-C.

Examples
    Test a condition
        [[ ${foo} == 'bar' ]] || ${CLI_COMMAND[@]} -- 'Foo does not equal bar.'
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

main() {
    ::cli::stderr::assert::inline "$@"
}

::cli::stderr::assert::inline() {
    if (( $# == 0 )); then 
        set 'Condition failed'
    fi

    {
        echo "ASSERT FAILED:" "$*"
        ::cli::bash::stack::trace::inline \
            | sed 's/^/  /'
    } | ::cli::stderr::dump::inline
}

self_test() {
    test() {
        set -m
        main "$@" 2>&1 1>/dev/stderr
    }

    diff <(test 'oops!') - <<-EOF || cli::assert
		ASSERT FAILED: oops!
		  main "oops!"                                       /Users/Setup/git/cli/src/stderr/assert:26
		  test "oops!"                                       /Users/Setup/git/cli/src/stderr/assert:44
		  self_test                                          /Users/Setup/git/cli/src/stderr/assert:47
		  cli stderr assert --self-test                      /Users/Setup/git/cli/cli:6
		EOF

    diff <(test) - <<-EOF || cli::assert
		ASSERT FAILED: Condition failed
		  main                                               /Users/Setup/git/cli/src/stderr/assert:26
		  test                                               /Users/Setup/git/cli/src/stderr/assert:44
		  self_test                                          /Users/Setup/git/cli/src/stderr/assert:55
		  cli stderr assert --self-test                      /Users/Setup/git/cli/cli:6
		EOF
}
