#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Verifies cli names convert them to bash names.

Description
    Argument \$1 is the name of the array to append results. 
    
    Assert remaining positional arguments match regex \${CLI_REGEX_NAME}.

    Replace dashes and period with underbar and store the result in \$1.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::name::to_bash::inline() {
    MAPFILE=()
    while (( $# > 0 )); do
        [[ "$1" =~ ${CLI_REGEX_NAME} ]] || cli::assert \
            "Unexpected cli name \"$1\" does not match regex ${CLI_REGEX_NAME}."

        MAPFILE+=( "${1//[-.]/_}" )
        shift
    done
}

self_test() {
    diff <(${CLI_COMMAND[@]} ---mapfile foo foo-bar .foo) - \
        <<-EOF || cli::assert
			foo
			foo_bar
			_foo
		EOF
}
