#!/usr/bin/env CLI_NAME=cli bash-cli
CLI_IMPORT=(
    'cli name to-bash'
    'cli bash join'
)

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Verifies cli names convert them to bash names.

Description
    Argument \$1 is the name of the array to append results. 
    
    Assert remaining positional arguments match regex '${CLI_REGEX_NAME}'.

    Replace dashes and period with underbar and store the result in \$1.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::name::to_inline::inline() {
    ::cli::name::to_bash::inline "$@"
    ::cli::bash::join::inline '::' '' "${MAPFILE[@]}" 'inline'
}

self_test() {
    to_inline() {
        ::cli::name::to_inline::inline "$@"
        echo "${REPLY}"

        ::cli::name::to_inline::inline "$@"
        local MY_REPLY="${REPLY}"
        [[ "${MY_REPLY}" == "${REPLY}" ]] || cli::assert
    }

    diff <(to_inline foo foo-bar .foo) - \
        <<< '::foo::foo_bar::_foo::inline' || cli::assert
}
