#!/usr/bin/env bash
source $(cli loader)
cli::import_group
cli::import cli_assert

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    Converts a stream of cli names to bash names.

Description
    Converts a stream of cli names to bash names. Fails if any of the
    cli names do not match regex ${CLI_REGEX_NAME}.

Arguments
    --result -r             : Array to store command name. Default: RESULT.

Global Arguments
    --help -h    [Flag] : Show this message and exit.
    --self-test  [Flag] : Runs a self test over all commands.

Examples
    Convert '.foo-bar' 'baz' to '_foo_bar' 'baz'
        ${CLI_COMMAND} <<< $'.foo-bar\nbaz'

EOF
}

inline() {
    local -a _result=()
    local -n ref_result=${arg_result:-RESULT}

    local args=( "$@" )
    while (( $# > 0 )); do
        if [[ ! "$1" =~ ${CLI_REGEX_NAME} ]]; then
            cli::fail "Unexpected cli name \"$1\"" \
                "found in \"${args[@]}\"" \
                "does not match regex ${CLI_REGEX_NAME}."
        fi
        ref_result+=( "${1//[-.]/_}" )
        shift
    done
}

main() {
    declare -a RESULT=()

    mapfile -t
    inline "${MAPFILE[@]}"
    IFS=$'\n'; echo "${RESULT[*]}"; unset IFS
}

self_test() {
    ${CLI_COMMAND} <<< $'.foo-bar\nbaz' \
    | assert::pipe_eq \
        "_foo_bar" \
        "baz"

    assert::fails "${CLI_COMMAND} <<< $'foo_bar'"
}

cli::main "$@"
