#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Remove each directory supplied as a positional argument.
EOF
}

main() {
    cli::io::dir::remove::inline "$@"
}

cli::io::dir::remove::inline() {
    rm -r -f "$@"
}

self_test() {
    cli::source cli-assert

    # create an empty temp dir
    local tempDirA="$(mktemp -d "${TMPDIR:-/tmp/}${CLI_TEMP_TEMPLATE}")"
    assert::directory_exists "${tempDirA}"

    # create a non-empty temp dir
    local tempDirB="$(mktemp -d "${TMPDIR:-/tmp/}${CLI_TEMP_TEMPLATE}")"
    local tempFileB="$(mktemp "${tempDirB}/${CLI_TEMP_TEMPLATE}")"
    assert::directory_exists "${tempDirB}"
    assert::file_exists "${tempFileB}"

    # remove both directories
    main "${tempDirA}" "${tempDirB}"
    assert::directory_does_not_exist "${tempDirA}"
    assert::directory_does_not_exist "${tempDirB}"
}

cli::main "$@"
