#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Set variable to the directory of the path.

Description
    Argument $1 is the name of the variable to set with the directory of the path.
    
    Argument $2 is a unix path. 
EOF
}

::cli::path::dir::inline() { 
    REPLY="$(dirname $1)"
}

self_test() {
    [[ "$(${CLI_COMMAND[@]} ---reply /foo)" == "/" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply /foo/)" == "/" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply foo/)" == "." ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ./foo-bar)" == "." ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply foo/bar)" == "foo" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ../..)" == ".." ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ../)" == "." ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ..)" == "." ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply /)" == "/" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ///)" == "/" ]] || cli::assert
}
