#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Set variable to the directory of the path.

Description
    Argument $1 is the name of the variable to set with the directory of the path.
    
    Argument $2 is a unix path. 
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::path::dir::inline() { 
    REPLY="$(dirname $1)"
}

self_test() {
    dir() { 
        ::cli::path::dir::inline "$@"
        echo ${REPLY}
    }

    [[ "$(dir /foo)" == "/" ]] || cli::assert
    [[ "$(dir /foo/)" == "/" ]] || cli::assert
    [[ "$(dir foo/)" == "." ]] || cli::assert
    [[ "$(dir ./foo-bar)" == "." ]] || cli::assert
    [[ "$(dir foo/bar)" == "foo" ]] || cli::assert
    [[ "$(dir ../..)" == ".." ]] || cli::assert
    [[ "$(dir ../)" == "." ]] || cli::assert
    [[ "$(dir ..)" == "." ]] || cli::assert
    [[ "$(dir /)" == "/" ]] || cli::assert
    [[ "$(dir ///)" == "/" ]] || cli::assert
}
