#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}

Summary
    Make a path absolute.

Description
    Argument $1 is the name of the variable to store the absolute path.

    Argument $2 is the path. If the path is already absolute, then it
    is assigned to the variable named by $1, otherwise the present working
    directory is prepened and then assigned to $1.

    If $2 is empty, then the present working directory is returned.

    If $2 begins with './', then that is stripped before prepending the
    present working directory.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::path::make_absolute::inline() {
    local -n REPLY_REF=$1
    shift

    if [[ ! "${1-}" ]]; then
        REPLY_REF="${PWD}"

    elif [[ ! "$1" =~ ^/ ]]; then
        REPLY_REF="${PWD}/${1##./}"

    else
        REPLY_REF="$1"
    fi
}

self_test() {
    make_absolute() {
        local REPLY
        ::cli::path::make_absolute::inline REPLY "$@"
        echo "${REPLY}"
    }

    [[ "$(make_absolute)" == "${PWD}" ]] || cli::assert
    [[ "$(make_absolute "foo/bar")" == "${PWD}/foo/bar" ]] || cli::assert
    [[ "$(make_absolute "./foo/bar")" == "${PWD}/foo/bar" ]] || cli::assert
    [[ "$(make_absolute "/foo/bar")" == "/foo/bar" ]] || cli::assert
}
