#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Set variable to the name of the path.

Description
    Argument $1 is the name of the variable to set with the name of the path.
    
    Argument $2 is a unix path. 
EOF
}

::cli::path::name::inline() { 
    REPLY="${1##*/}"; 
}

self_test() {
    [[ "$(${CLI_COMMAND[@]} ---reply /foo)" == "foo" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply ./foo-bar)" == "foo-bar" ]] || cli::assert
    [[ "$(${CLI_COMMAND[@]} ---reply foo/bar)" == "bar" ]] || cli::assert
}
