#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}

Summary
    Set variable to the name of the path.

Description
    Argument $1 is the name of the variable to set with the name of the path.
    
    Argument $2 is a unix path. 
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::path::name::inline() { 
    local -n REPLY_REF=$1
    REPLY_REF="${2##*/}"; 
}

self_test() {
    name() { 
        local REPLY
        ::cli::path::name::inline REPLY "$@"
        echo ${REPLY}
    }

    [[ "$(name /foo)" == "foo" ]] || cli::assert
    [[ "$(name ./foo-bar)" == "foo-bar" ]] || cli::assert
    [[ "$(name foo/bar)" == "bar" ]] || cli::assert
}
