#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Check an argument value is valid.

Description
    Given an argument value and associated metadata, fail if the value violates
    constraints specified by the metadata. The value can be a boolean, integer,
    or string. Elements and values of arrays and maps are passed one by one to 
    this function for validation.
    
    Positional arguments are:

        - name
        - value
        - type (boolean, integer, string)
        - required
        - regex
        - allowed values
        - min
        - max

    Empty metadata values imply no validation for that dimention of metadata.

Arguments
    --                       : 
EOF
    cat << EOF

Examples
    cli args check -- value "hello world" 'string' true '[a-z ]*' '' '' ''
EOF
}

main() {
    ::cli::args::check::inline "$@"
}

::cli::args::check::inline() {
    local name="$1"
    local value="${2-}"
    local type=${3:-'string'}
    local regex=${4:-}
    local -a allow=( ${5:-} )
    local min=${6:-0}
    local max=${7:-1000000}

    # type
    case ${type} in
        'string') ;;
        'integer') regex='^[-]?[0-9]+$' ;;
        'boolean') regex='^true$|^false$|^$' ;;
        *) cli::fail "Unexpected argument type '${type}' for argument '--${name}'."
    esac

    # regex
    if [[ -n "${regex}" ]]; then
        if [[ ! "${value}" =~ ${regex} ]]; then
            cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                "passed to command '${CLI_COMMAND}'." \
                "Expected a value that matches regex '${regex}'."
        fi
    fi

    # allow
    if (( ${#allow[@]} > 0 )); then

        # convert array of allowed value into a set
        local -A set
        local element
        for element in "${allow[@]}"; do
            set[$element]="true"
        done

        if [[ -z "${value}" || -z ${set[${value}]+set} ]]; then
            cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                "passed to command '${CLI_COMMAND}'." \
                "Expected a value in the set { "${!set[@]}" }."
        fi
    fi

    # max/min
    case ${type} in
        'string') 
            if (( ${#value} < ${min} )); then
                cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                    "passed to command '${CLI_COMMAND}'." \
                    "Expected a value whose length is at least ${min}."
            fi
            if (( ${#value} > ${max} )); then
                cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                    "passed to command '${CLI_COMMAND}'." \
                    "Expected a value whose length is no more than ${max}."
            fi
            ;;
        'integer') regex='[-]?[0-9]+' 
            if (( ${value} < ${min} )); then
                cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                    "passed to command '${CLI_COMMAND}'." \
                    "Expected a value that is at least ${min}."
            fi
            if (( ${value} > ${max} )); then
                cli::fail "Unexpected value '${value}' for argument '--${name}'" \
                    "passed to command '${CLI_COMMAND}'." \
                    "Expected a value that is no more than ${max}."
            fi
        ;;
    esac
}

self_test() {
    cli args check -- myname myvalue
    cli args check -- myname true 'boolean'
    cli args check -- myname false 'boolean'
    cli args check -- myname '' 'boolean'
    cli args check -- myname myvalue 'string' '.*' 'myvalue myothervalue' 0 100
    cli args check -- myname myothervalue 'string' '.*' 'myvalue myothervalue' 0 100

    assert::fails "${CLI_COMMAND} -- myname '' 'integer'" \
        "Unexpected value '' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value that matches regex '^[-]?[0-9]+$'."

    assert::fails "${CLI_COMMAND} -- myname rando 'boolean'" \
        "Unexpected value 'rando' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value that matches regex '^true$|^false$|^$'."

    assert::fails "${CLI_COMMAND} -- myname Foo string \"^[a-z]$\"" \
        "Unexpected value 'Foo' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value that matches regex '^[a-z]$'."

    assert::fails "${CLI_COMMAND} -- myname Foo string '' \"Bar\"" \
        "Unexpected value 'Foo' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value in the set { Bar }."

    assert::fails "${CLI_COMMAND} -- myname Foo string '' '' 10" \
        "Unexpected value 'Foo' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value whose length is at least 10."

    assert::fails "${CLI_COMMAND} -- myname Foo string '' '' 0 2" \
        "Unexpected value 'Foo' for argument '--myname' passed to command 'cli args check'." \
        "Expected a value whose length is no more than 2."

    assert::fails "${CLI_COMMAND} -- myname 5 integer '' '' 10" \
        "Unexpected value '5' for argument '--myname' passed to command '${CLI_COMMAND}'." \
        "Expected a value that is at least 10."

    assert::fails "${CLI_COMMAND} -- myname 5 integer '' '' 0 2" \
        "Unexpected value '5' for argument '--myname' passed to command 'cli args check'." \
        "Expected a value that is no more than 2."
}

cli::main "$@"