#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Tokenizes command line arguments.

Description
    Tokenizes command line arguments. Theoretically, a command line could be 
    matched by a regular expression. This command effectively does that match
    and emits 
    
        an array of paths
        an associative array of named arguments (aka options), and 
        an array of positional arguments (aka arguments)

    For example, 
    
        ${CLI_COMMAND[@]} -- bin sequence --name even -v -- two four six 
        
    produces:

        path bin
        path sequence
        option name even
        option v true
        argument two
        argument four
        argument six

    The command line syntax is based off the Azure az tool with the additon that:
    
        1. multipule single character options can be included behind the 
           same single dash with the last option optionally having a value.
        2. arguments following '--' are positional arguments. 
        
    For example, 

       '-gh v' 
        
    produces: 
    
        option g true
        option h v

    Options proceeded by a double dash must be composed of lowercase letters, numbers, 
    or dash, and must start with a letter. 
    
    Options behind a single dash must be a lowercase letter.

    If an internal flag (e.g. '---which') appears before the first option, then
    parsing ends with success.

Arguments
    --                      : Command line arguments.
EOF
    cat << EOF

Examples
    Tokenize 'bin cli --k0 v0 --flag -xyz v1 -- a0 a1'.
        ${CLI_COMMAND[@]} -- bin cli --k0 v0 --flag -xyz v1 -- a0 a1
EOF
}

cli::args::tokenize::main() {   
    cli::declare 'cli_tokens' TOKENS

    ARG_TOKENS=TOKENS \
        ::cli::args::tokenize::inline "$@"

    for i in "${!TOKENS_ID[@]}"; do
        echo ${CLI_ARG_TOKEN[TOKENS_ID[$i]]} "${TOKENS_IDENTIFIER[$i]-}"
    done
}

::cli::args::tokenize::inline() {
    : ${ARG_TOKENS?}
    local -n TOKEN_REF="${ARG_TOKENS}_ID"
    local -n IDENTIFIER_REF="${ARG_TOKENS}_IDENTIFIER"

    local NAME_REGEX='[a-z][a-z0-9-]*'

    local CLI_REGEX_NAME="^[a-z.][a-z0-9-]*$"

    local DASH_REGEX="^-[^-].*$" # enable better error messages
    local DASH_FLAGS_REGEX="^-([a-z]+)$"

    local DASH_DASH_REGEX="^--[^-].*$" # enable better error messages
    local DASH_DASH_OPTION_REGEX="^--(${NAME_REGEX})$"

    local DASH_DASH_DASH_REGEX="^---[^-].*$" # enable better error messages
    local DASH_DASH_DASH_OPTION_REGEX="^---(${NAME_REGEX})$"

    local DASH_DASH='--'

    yield() {
        TOKEN_REF+=( $1 )
        IDENTIFIER_REF+=( "${2-}" )
    }

    while (( $# > 0 )); do
        if [[ "$1" =~ ${CLI_REGEX_NAME} ]]; then
            yield ${CLI_ARG_TOKEN_PATH} "$1"
        else
            break
        fi

        shift
    done
    
    while (( $# > 0 )); do        
        if [[ "$1" =~ ${DASH_REGEX} ]]; then

            if [[ ! "$1" =~ ${DASH_FLAGS_REGEX} ]]; then
                cli::fail "Unexpected option \"$1\"" \
                    "does not match regex ${DASH_FLAGS_REGEX}" \
                    "passed to command \"${CLI_COMMAND[@]}\"."
            fi

            yield ${CLI_ARG_TOKEN_DASH} "${BASH_REMATCH[1]}"

        elif [[ "$1" =~ ${DASH_DASH_REGEX} ]]; then
                
            if [[ ! "$1" =~ ${DASH_DASH_OPTION_REGEX} ]]; then
                cli::fail "Unexpected option \"$1\"" \
                    "does not match regex ${DASH_DASH_OPTION_REGEX}" \
                    "passed to command \"${CLI_COMMAND[@]}\"."
            fi

            yield ${CLI_ARG_TOKEN_DASH_DASH} "${BASH_REMATCH[1]}"

        elif [[ "$1" =~ ${DASH_DASH_DASH_REGEX} ]]; then

            if [[ ! "$1" =~ ${DASH_DASH_DASH_OPTION_REGEX} ]]; then
                cli::fail "Unexpected option \"$1\"" \
                    "does not match regex ${DASH_DASH_DASH_OPTION_REGEX}" \
                    "passed to command \"${CLI_COMMAND[@]}\"."
            fi

            yield ${CLI_ARG_TOKEN_DASH_DASH_DASH} "${BASH_REMATCH[1]}"

        elif [[ "$1" == ${DASH_DASH} ]]; then
            yield ${CLI_ARG_TOKEN_END_OPTIONS}
            shift

            while (( $# > 0 )); do
                yield ${CLI_ARG_TOKEN_VALUE} "$1"
                shift
            done

            break
        else
            yield ${CLI_ARG_TOKEN_VALUE} "$1"
        fi

        shift
    done

    yield ${CLI_ARG_TOKEN_EOF}
}

self_test() {
    ${CLI_COMMAND[@]} \
        | assert::pipe_eq \
            'EOF '

    # positional argument delimiter (e.g. --)
    ${CLI_COMMAND[@]} -- \
        | assert::pipe_eq \
            'EOF '
   
    # basic
    ${CLI_COMMAND[@]} -- c --k v -- a0 \
        | assert::pipe_eq \
            'PATH c' \
            'DASH_DASH k' \
            'VALUE v' \
            'END_OPTIONS ' \
            'VALUE a0' \
            'EOF '
    # escape
    ${CLI_COMMAND[@]} -- --k 'v v' -- 'a a' \
        | assert::pipe_eq \
            'DASH_DASH k' \
            'VALUE v v' \
            'END_OPTIONS ' \
            'VALUE a a' \
            'EOF '

    # named argument default aliasing (e.g. '-k' -> '--k' )
    ${CLI_COMMAND[@]} -- -k v \
        | assert::pipe_eq \
            'DASH k' \
            'VALUE v' \
            'EOF ' 

    # named argument packed (e.g. '-mn' -> '--m --n' )
    ${CLI_COMMAND[@]} -- -mn \
        | assert::pipe_eq \
            'DASH mn' \
            'EOF '

    # named argument implicit value (e.g. '' )
    ${CLI_COMMAND[@]} -- --m -n \
        | assert::pipe_eq \
            'DASH_DASH m' \
            'DASH n' \
            'EOF '

    # path
    ${CLI_COMMAND[@]} -- g0 g1 cmd \
        | assert::pipe_eq \
            'PATH g0' \
            'PATH g1' \
            'PATH cmd' \
            'EOF '

    # positional
    ${CLI_COMMAND[@]} -- -- a0 a1 \
        | assert::pipe_eq \
            'END_OPTIONS ' \
            'VALUE a0' \
            'VALUE a1' \
            'EOF '

    assert::fails "${CLI_COMMAND[@]} -- -!" \
        "Unexpected option \"-!\" does not match regex ^-([a-z]+)$" \
        "passed to command \"cli args tokenize\"."

    assert::fails "${CLI_COMMAND[@]} -- --!" \
        "Unexpected option \"--!\" does not match regex ^--([a-z][a-z0-9-]*)$" \
        "passed to command \"cli args tokenize\"."

    assert::fails "${CLI_COMMAND[@]} -- ---!" \
        "Unexpected option \"---!\" does not match regex ^---([a-z][a-z0-9-]*)$" \
        "passed to command \"cli args tokenize\"."
}
