#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_parent_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Prevents the target method from appearing in stack traces.
EOF
}

declare -A CLI_TYPE_CLI_BASH_STACK_HIDDEN_ATTRIBUTE=()

main() {
    cli::export CLI_TYPE_CLI_BASH_STACK
}

cli::main "$@"