#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert
cli::import_group
cli::import_inline cli core declare

help() {
    cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Read a list of records into a variable.

Description
    Reads records and for each record write the record to a variable by
    calling 'cli core declare'.

Arguments
    ${CLI_CORE_ARG_NAME}
    ${CLI_CORE_ARG_TYPE}

Debug Arguments
    --source -s      [Flag] : Source stdin.

Global Arguments
    ${CLI_GLOBAL_ARG_HELP}
    ${CLI_GLOBAL_ARG_SELF_TEST}
EOF
}

inline() {
    return
}

main() {
    return
}

self_test() {
    echo 'Hello\ World!' \
        ${CLI_COMMAND} --name STRING
        
    declare STRING='Hello World!'
    declare -p STRING \
        | cli core write --source --name STRING --type string \
        | assert::pipe_eq_exact \
            
}

cli::load "$@"