#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Copies stdin to a temporary file and echos the path to the file.
EOF
}

::cli::bash::dump::inline() {
    
}

self_test() {
    cli::source cli-assert
}
