#!/usr/bin/env bash
source /dev/stdin < <(cli loader)

help() {
cat << EOF
Command
    cli find : find commands and groups of a cli.

Arguments
    --cli -c                : Name of cli.
    --traversal             : Specify the type of traversal. Allowed values:
                              pre, post. Default: pre.

Primary Arguments
    --type                  : True if type of entry is of the specified type.
                              Allowed values: 'c', 'g', ''.
    --ls             [Flag] : True. Prints out the type (either 'c' or 'g') 
                              followed by the entry.
    --name                  : True if the last component of the path name being
                              examined matches the pattern.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    List commands and groups of 'cli' in post-order
        cli find --cli cli --ls --traversal post

    List groups of 'cli'
        cli find --cli cli --type g

    List emit commands of 'cli'
        cli find --cli "cli emit" --type c
EOF
}

find() {
    local node="$*"

    # post-order traversal
    if [[ ${arg_traversal} == 'post' ]]; then
        visit_children "${node}"
    fi

    visit 'g' "${node}"

    # pre-order traversal
    if [[ ${arg_traversal} == 'pre' ]]; then
        visit_children "${node}"
    fi
}

visit_children() {
    local node="$1"
    local type
    local name

    ${node} | while read type name; do {
        if [[ "${type}" == 'c' ]]; then
            visit 'c' "${node} ${name}"
        else
            find "${node}" "${name}"
        fi
    }
    done
}

visit() {
    local type=$1
    local path=$2
    local name=${path##* }

    if predicate "${type}" "${name}"; then
        
        # select type
        if $arg_ls; then 
            echo -n "${type} "
        fi

        # select full command name
        echo ${path}
    fi
}

predicate() {
    local type=$1
    local name=$2

    # filter by type
    if [[ ! "${arg_type}" == '' ]]; then
        if [[ ! "${arg_type}" == "${type}" ]]; then 
            return 1
        fi
    fi

    # filter by name
    if [[ -n "${arg_name}" ]]; then
        if [[ ! "${name}" == ${arg_name} ]]; then 
            return 1
        fi
    fi
}

main() {
    find "${arg_cli}"
}

cli::load "$@"