#!/usr/bin/env CLI_NAME=cli bash-cli-part

cli::find::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Find commands and groups of a cli.

Arguments
    --traversal             : Specify the type of traversal. Allowed values:
                              pre, post. Default: pre.
    --

Primary Arguments
    --type -t               : True if type of entry is of the specified type.
                              Allowed values: c, g.
    --name -n               : True if the last component of the path name being
                              examined matches the pattern.
    --ls             [Flag] : True. Prints out the type (either 'c' or 'g') 
                              followed by the entry.
EOF
    cat << EOF

Examples
    List commands and groups of 'cli' in post-order
        ${CLI_COMMAND[@]} --ls --traversal post -- cli

    List groups of 'cli'
        ${CLI_COMMAND[@]} --type g -- cli

    List emit commands of 'cli'
        ${CLI_COMMAND[@]} --type c --cli cli emit
EOF
}

find() {
    local NODE="$*"

    # post-order traversal
    if [[ ${ARG_TRAVERSAL} == 'post' ]]; then
        visit_children "${NODE}"
    fi

    visit 'g' "${NODE}"

    # pre-order traversal
    if [[ ${ARG_TRAVERSAL} == 'pre' ]]; then
        visit_children "${NODE}"
    fi
}

visit_children() {
    local NODE="$1"
    local TYPE
    local NAME

    cli list -- ${NODE} | while read TYPE NAME; do {
        if [[ "${TYPE}" == 'c' ]]; then
            visit 'c' "${NODE} ${NAME}"
        else
            find "${NODE}" "${NAME}"
        fi
    }
    done
}

visit() {
    local TYPE=$1
    local PTH=$2
    local NAME=${PTH##* }

    if predicate "${TYPE}" "${NAME}"; then
        
        # select TYPE
        if ${ARG_LS}; then 
            echo -n "${TYPE} "
        fi

        # select full command NAME
        echo ${PTH}
    fi
}

predicate() {
    local TYPE=$1
    local NAME=$2

    # filter by TYPE
    if [[ ! "${ARG_TYPE}" == '' ]]; then
        if [[ ! "${ARG_TYPE}" == "${TYPE}" ]]; then 
            return 1
        fi
    fi

    # filter by NAME
    if [[ -n "${ARG_NAME}" ]]; then
        if [[ ! "${NAME}" == ${ARG_NAME} ]]; then 
            return 1
        fi
    fi
}

cli::find::main() {
    find "$@"
}
