#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Find transitive imports for a list of imports.

Arguments
    --cli -c                : CLI path to a command or group.
    --tree -t        [Flag] : Indent output.
    --unique -u      [Flag] : Print only unique imports.
    --resolve -r     [Flag] : Print the file to which the import 
                              resolves after printing the import.
    --                      : List of imports.
EOF
    cat << EOF

Examples
    Emit the unique sorted imports of 'cli dsl'
        cli imports -c "cli dsl"
EOF
}

cli::imports::recurse() {

    while (( $# > 0 )); do
        local import=$1
        shift

        if ${ARG_UNIQUE} && ${seen[$import]-false}; then
            continue
        fi

        echo "${prefix}${import}"
        seen["${import}"]=true

        if ${ARG_RESOLVE}; then
            echo "${prefix}$(${import} ---which)"
        fi

        ( 
            local -a CLI_LOADER_IMPORTS=()
            source $(${import} '---exports')

            if (( ${#CLI_LOADER_IMPORTS[*]} > 0 )); then
                printf '%s\n' "${CLI_LOADER_IMPORTS[@]}"
            fi
        ) | mapfile -t

        prefix="${prefix}${indent}" cli::imports::recurse "${MAPFILE[@]}"
    done 
}

cli::imports::command() {
    $1 '---imports' | mapfile -t
    if ${ARG_TREE}; then
        echo $1
    fi
    prefix="${prefix}${indent}" cli::imports::recurse "${MAPFILE[@]}"
}

cli::imports::group() {
    cli find --cli "${ARG_CLI}" --type 'c' \
        | while read; do cli::imports::command "${REPLY}"; done
}

main() {
    local prefix=
    local indent=
    local -A seen=

    if ${ARG_TREE}; then
        indent='  '
    fi

    cli::imports::recurse "$@"

    if [[ -n "${ARG_CLI}" ]]; then
        case $(${ARG_CLI} '---type') in
            'command') cli::imports::command "${ARG_CLI}" ;;
            'group') cli::imports::group ;;
        esac
    fi
}

cli::main "$@"