#!/usr/bin/env bash
source $(cli loader)

help() {
cat << EOF
Command
    cli imports : find set of transitive imports for a cli.

Arguments
    --cli -c     [Required] : Name of a cli command.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Emit the unique sorted imports of 'cli dsl'
        cli imports -c "cli dsl"
EOF
}

main() {
    cli find --cli "${arg_cli}" --type c \
        | while read; do
            ${REPLY} '---imports' &
        done \
    | sort -u
}

cli::load "$@"