#!/usr/bin/env bash
source $(cli loader)
cli::import cli_emit

help() {
    cat << EOF
Command
    cli pack

Summary
    Package a group of commands into a into a single file.
    
Description
    Recursively discover cli commands developed as individual files
    and hosted in a specified directory, and package them into a 
    single file. For example, a cli 'integrate' with commands 'circle',
    'square', 'cube', 'sphere' could be arranged as a files 'integrate', 
    'circle', 'square', 'cube', 'square' and '.group' in a directory 'src':

        integrate
        src/.group
        src/area/.group
        src/area/square
        src/area/circle
        src/volume/.group
        src/volume/circle
        src/volume/circle
    
    File 'integrate' must be on the path and contain:

        #!/usr/bin/env bash
        cli shim "\$(dirname \${BASH_SOURCE})/src" "\$@"

    The remaining files must all start with the following:
    
        #!/usr/bin/env bash
        source $(cli loader)

    This will define 'cli::import' and 'cli::export' and 'cli::export_import'.
    Commands must use 'cli::import' instead of 'source' to reference libraries. 
    Libraries use 'cli::export' to emit functions and variables with common 
    prefixes and 'cli::export_import' to reference other libraries. 

    For example, 'src/.group' could define and export 'integrate::multiply' and
    'INTEGRATE_PI' like this:

        #!/usr/bin/env bash
        source $(cli loader)
        main() { cli::export 'integrate'; }
        INTEGRATE_PI='3.14159'
        integrate::multiply() { IFS='*' expr=\$*; echo "\$expr" | bc -l; }
        cli::load "\$@"

    then 'src/area/.group' could import 'src/.group' and use it to
    define and export 'integrate::area::square':

        #!/usr/bin/env bash
        source $(cli loader)
        main() { 
            cli::export_import integrate .group
            cli::export integrate area
        }
        integrate::area::square() { integrate::multiply \$1 \$1; }
        cli::load "\$@"

     finally 'circle' could reference 'src/area/.group' like this:

        #!/usr/bin/env bash
        source $(cli loader)
        source /dev/stdin < <(cli::import integrate area .group)
        help() {
            echo "Arguments"
            echo "    --radius     [Required] : Radius of the circle."
        }
        main() { 
            echo \$(integrate::multiply \${INTEGRATE_PI} \\
                \$(integrate::area::square \${arg_radius}))
        }
        cli::load "\$@"
        
    To pack the 'area' cli into a single file:

        cli pack --dir src --name area --output-dir /usr/bin

Arguments
    --cli -c        [Required] : Name of the cli.

Global Arguments
    --help -h           [Flag] : Show this message and exit.
    --self-test         [Flag] : Runs a self test.
    --dry-run           [Flag] : Show a table of content of the commands and
                                 libraries that would be packed.
EOF
}

main() (
    if ${arg_dry_run}; then
        table_of_content
    else
        local path="${arg_output_dir}/${arg_name}"
        if [[ -f ${path} ]]; then rm ${path}; fi
        emit > "${path}"
        chmod a+x "${path}"
    fi
)

emit() {
    emit::shebang
    echo

    # commands
    cli emit commands "${arg_name}" \
        | emit_section 'Commands'

    # libraries
    cli emit libraries "${arg_name}" \
        | emit_section 'Libraries'

    # reflection
    cli emit entries \
        | emit::function 'cli::shim::list' \
        | emit_section 'Reflection'

    # initializers
    cli emit initializers "${arg_name}" \
        | emit_section 'Initializers'

    # loader
    cli loader ---pack \
        | emit_section 'Loader'

    # shim
    cli shim \
        | emit_section 'Shim'

    echo "cli::shim::main ${arg_name} \"\$@\""
}

emit_section() {
    echo \#
    echo \# $1
    echo \#
    while read -r; do echo "${REPLY}"; done
    echo
}

self_test() (
    return
)

cli::load "$@"