#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::source cli path get-info

cli::list::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    List the command in a group.

Description
    Given a path to a directory, list the executable files and sub-directories
    on separate lines preceeded by a 'c' (for command) or 'g' (for group). 
    Results are sorted by the name of the directory or file. Files or directories 
    that start with dot are included. Output is sorted by commands, then groups,
    then by name.

Arguments
    -- : The cli group.
EOF
    cat << EOF

Examples
    List commands in '/usr/bin'
        cli list --dir /usr/bin
EOF
}

cli::list::main() (
    local DIR=$(dirname $($@ .group ---which))

    # include dot files
    local GLOB='* .[^.]*'

    cd "${DIR}"

    # print '<type> <name>'
    for ENTRY in ${GLOB}; do

        # exclude cache directory
        if [[ "${ENTRY}" == '.cli' ]]; then
            continue
        fi

        cli::path::get_info "${ENTRY}"

        if ! ${REPLY_CLI_PATH_IS_FILE} && ! ${REPLY_CLI_PATH_IS_DIRECTORY}; then 
            continue
        fi

        if ! ${REPLY_CLI_PATH_IS_EXECUTABLE}; then 
            continue
        fi

        # print type
        if ${REPLY_CLI_PATH_IS_FILE}; then

            if [[ ${ENTRY} == *.sh ]]; then
                ENTRY=${ENTRY%.sh}
            fi

            echo -n 'c' # command

        elif ${REPLY_CLI_PATH_IS_DIRECTORY}; then 

            echo -n 'g' # group
        else 
            continue
        fi

        # print name
        echo " ${ENTRY}"
    done | sort -k2
)
