#!/usr/bin/env CLI_TOOL=cli bash-cli-part
CLI_IMPORT=(
    "cli_emit"
)

cli::pack::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Package a group of commands into a into a single file.

Description
    Recursively discover cli commands developed as individual files
    and hosted in a specified directory, and package them into a
    single file. For example, a cli 'integrate' with commands 'circle',
    'square', 'cube', 'sphere' could be arranged as a files 'integrate',
    'circle', 'square', 'cube', 'square' and '.group' in a directory 'src':

        integrate
        src/.group
        src/area/.group
        src/area/square
        src/area/circle
        src/volume/.group
        src/volume/circle
        src/volume/circle

    File 'integrate' must be on the path and contain:

        #!/usr/bin/env bash
        cli shim "\$(dirname \${BASH_SOURCE})/src" "\$@"

    The remaining files must all start with the following:

        #!/usr/bin/env bash
        source $(cli loader ---exports)

    This will define 'cli::source' and 'cli::export' and 'cli::export_import'.
    Commands must use 'cli::source' instead of 'source' to reference libraries.
    Libraries use 'cli::export' to emit functions and variables with common
    prefixes and 'cli::export_import' to reference other libraries.

    For example, 'src/.group' could define and export 'integrate::multiply' and
    'INTEGRATE_PI' like this:

        #!/usr/bin/env bash
        source $(cli loader ---exports)
        main() { cli::export 'integrate'; }
        INTEGRATE_PI='3.14159'
        integrate::multiply() { IFS='*' expr=\$*; echo "\$expr" | bc -l; }
        cli::main "\$@"

    then 'src/area/.group' could import 'src/.group' and use it to
    define and export 'integrate::area::square':

        #!/usr/bin/env bash
        source $(cli loader ---exports)
        main() {
            cli::export_import integrate .group
            cli::export integrate area
        }
        integrate::area::square() { integrate::multiply \$1 \$1; }
        cli::main "\$@"

     finally 'circle' could reference 'src/area/.group' like this:

        #!/usr/bin/env bash
        source $(cli loader ---exports)
        source /dev/stdin < <(cli::source integrate area .group)
        help() {
            echo "Arguments"
            echo "    --radius     [Required] : Radius of the circle."
        }
        main() {
            echo \$(integrate::multiply \${INTEGRATE_PI} \\
                \$(integrate::area::square \${arg_radius}))
        }
        cli::main "\$@"

    To pack the 'area' cli into a single file:

        cli pack --dir src --name area --output-dir /usr/bin

Arguments
    --cli -c        [Required] : Name of the cli.
    --dry-run           [Flag] : Show a table of content of the commands and
                                 libraries that would be packed.
EOF
}

# shim functions abstracting paths
CLI_SHIM_NAMESPACE='cli::shim'
CLI_SHIM_IS_COMMAND="${CLI_SHIM_NAMESPACE}::is_command"
CLI_SHIM_IS_GROUP="${CLI_SHIM_NAMESPACE}::is_group"
CLI_SHIM_LIST="${CLI_SHIM_NAMESPACE}::list"

entries() {
    cli find --cli "${arg_cli}" --type "$1"
}

groups() {
    entries 'g'
}

commands() {
    entries 'c'
}

emit_is_command() {
    commands \
        | cli emit contains --name "${CLI_SHIM_IS_COMMAND}"
}

emit_is_group() {
    groups \
        | cli emit contains --name "${CLI_SHIM_IS_GROUP}"
}

emit_case_statement() {
    cli emit case-statement --cli "${arg_cli}" \
        | emit::function "${CLI_SHIM_LIST}"
}

emit_commands() {
    commands \
        | while read; do cli emit subproc --cli "${REPLY}"; done \
        | emit_section 'Commands'
}

emit_libraries() {
    commands \
        | while read; do cli imports --cli "${REPLY}"; done \
        | sort -u \
        | while read; do cli emit source --cli "${REPLY}"; done \
        | emit_section 'Libraries'
}

emit_reflection() {
    cat \
        <(emit_is_command) \
        <(emit_is_group) \
        <(emit_case_statement) \
        | emit_section 'Reflection'
}

emit_initializers() {
    commands \
        | while read; do cli emit define-initialize --cli "${REPLY}"; done \
        | emit_section 'Initializers'
}

main() {
    emit::shebang
    echo

    # body (emit in parallel)
    cat \
        <(emit_commands) \
        <(emit_libraries) \
        <(emit_initializers) \
        <(emit_reflection)

    # emit_commands
    # emit_libraries
    # emit_initializers
    # emit_reflection

    # loader
    cli loader ---pack \
        | emit_section 'Loader'

    # shim
    cli shim \
        | emit_section 'Shim'

    echo "cli::shim::main ${arg_cli} \"\$@\""
}

emit_section() {
    echo \#
    echo \# $1
    echo \#
    while read -r; do echo "${REPLY}"; done
    echo
}

self_test() (
    return
)
