#!/usr/bin/env CLI_TOOL=cli bash-cli-part
CLI_IMPORT=(
    "cli bash emit expression declare"
    "cli bash emit initializer array"
    "cli bash emit statement assignment"
    "cli cache put"
)

cli::replace::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Summary
    Replace help with command::name::help.

Arguments
    -- : The cli group.
EOF
}

process() {
    local CLI="$@"
    local SOURCE=$(${CLI} ---path)
    local -a IMPORTS=()

    MAPFILE=()
    ${CLI} ---imports | sort -u | mapfile -t
    IMPORTS=( "${MAPFILE[@]}" )

    echo ${SOURCE} >&2
    if (( ${#IMPORTS[@]} == 0 )); then
        return
    fi

    local BASH=$(
        cli::bash::emit::statement::assignment \
            <(echo -n CLI_IMPORT) \
            <(cli::bash::emit::initializer::array IMPORTS) \
    )

    sed -i '' '/^cli::source.*/d' "${SOURCE}"

    cat "${SOURCE}" \
        | {
            read
            echo "${REPLY}"
            echo "${BASH}"
            cat
        } | cli::cache::put "${SOURCE}"
    chmod a+x "${SOURCE}" 
}

cli::replace::main() (
    cli find -t c -- "$@" \
        | while read; do process ${REPLY}; done
)
