#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}
    
Summary
    Run a command as a different user.

Arguments
    --command -c [Required] : The path to the command.
    --user -u    [Required] : The name of the user.
    --                      : Arguments.
EOF
    cat << EOF

Examples
    Test for the function 'inline'.
        ${CLI_COMMAND} --name inline
EOF
}

cli::meta::declare() {
    cli::meta::add_required 'command'
    cli::meta::add_required 'user'
    cli::meta::allow_positional
}

::cli::run_as::inline() {
    local -a args=($(printf %q "${arg_command}"))

    for i in "$@"; do
        args+=( $(printf %q "${i}") )
    done

    sudo su "${arg_user}" -c "${args[*]}"
}

self_test() {
    return
    # TODO create user, test, delete user
}

cli::main "$@"