#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert

help() {
cat << EOF
Command
    ${CLI_COMMAND}
    
Summary
    Run a command as a different user.

Arguments
    --command -c [Required] : The path to the command.
    --user -u    [Required] : The name of the user.
    --                      : Arguments.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Test for the function 'inline'.
        ${CLI_COMMAND} --name inline
EOF
}

inline() {
    local -a args=($(printf %q "${arg_command}"))

    for i in "$@"; do
        args+=( $(printf %q "${i}") )
    done

    sudo su "${arg_user}" -c "${args[*]}"
}

self_test() {
    return
    # TODO create user, test, delete user
}

cli::load "$@"