#!/usr/bin/env bash
source $(cli loader)
cli::import_group

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}

Summary
    Run a self test for every command. 
    
Description
    Commands are found via recursive search starting at '--dir'.
    Those commands are then invoked with the flag '--self-test'.
    If all test succeed, the exit code is 0, otherwise 1.

Arguments
    --dir                   : The directory to start searching for commands.
EOF
}

import() {
    cli::meta::add_required 'dir'
}

report() {
    local command="$1"

    # interpret no output as a success
    if ! read result; then
        return
    fi

    # interpret any output as a failure
    exit_code=1
    echo "${command}"
    cat <(echo ${result}) - | sed 's/^/>   /'
}

main() {
    local exit_code=0

    cd "${arg_dir}"

    # search for commands starting at --dir
    cli find commands --recursive | {
        while read command; do 

            if $arg_dry_run; then
                echo "${command} --self-test"
                continue
            fi

            # execute each command's self test
            "${command}" --self-test 2>&1 | report "${command}"
        done
    }

    exit "${exit_code}"
}

cli::main "$@"