#!/usr/bin/env CLI_NAME=cli bash-cli-part

cli::test::help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Test.
EOF
}

cli::test::main() {
    echo "TESTING!"
    echo "CLI_COMMAND=${CLI_COMMAND-}, \$0=$0, args=$@"
    # declare -p CLI_LOADER_IMPORT CLI_LOADER_SOURCED CLI_LOADER_CACHE_SOURCED_PATHS CLI_TYPE
    # cli::assert 'WE DID IT!'
    # cli::test_inline a b c
}
