#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Test.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::test_inline::inline() {
    echo 'Hello world!' "$@"
}