#!/usr/bin/env bash
source /dev/stdin < <(cli loader)
source /dev/stdin < <(cli::import cli emit .group)

help() {
    cat << EOF
Command
    cli emit contains : Emit a path predicate.

Arguments
    --name -n    [Required] : Name of the function.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Emit a predicate that test if a path is a command.
        cli find --cli cli --type c \
            | cli emit contains --name is_command

    Emit a predicate that test if a path is a group.
        cli find --cli cli --type g \
            | cli emit contains --name is_group
EOF
}

main() (
    while read; do cli::emit::library_name ${REPLY}; done \
        | emit::function_contains ${arg_name}
)

cli::load "$@"