#!/usr/bin/env bash
source $(cli loader)

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    Emit functions for exporting functions, variables, and import statements.
    
Description

Global Arguments
    --help -h       : Show this message and exit.
    --self-test     : Runs a self test.
EOF
}

cli::export::functions() {
    local glob

    for i in "$@"; do 
        glob+="${i}::"
    done

    while read keyword flags name; do
        if [[ "${name}" == ${glob}* ]]; then
            declare -f "${name}"
        fi
    done < <(declare -F)
}

cli::export::variables() {
    local -u glob

    for i in "$@"; do 
        glob+="${i}_"; 
    done

    for i in $(eval echo "\${!${glob}@}"); do
        declare -p "${i}" \
            | sed 's/^declare/declare -g/'
    done
}

cli::export::import() {
    echo "cli::import $@"
}

cli::export::import_group() {
    local segments=( ${CLI_COMMAND} )
    local length=${#segments[@]}
    local group="${segments[@]:0:$(( length - 1 ))}"
    echo "cli::import ${group} .group"
}

cli::export::import_parent_group() {
    local segments=( ${CLI_COMMAND} )
    local length=${#segments[@]}
    local parent_group="${segments[@]:0:$(( length - 2 ))}"
    echo "cli::import ${parent_group} .group"
}

cli::export() {
    cli::export::variables "$@"
    cli::export::functions "$@"
}

main() {
    declare -f cli::export
    declare -f cli::export::import
    declare -f cli::export::import_group
    declare -f cli::export::import_parent_group
    declare -f cli::export::variables
    declare -f cli::export::functions
}

initialize() {
    : ${arg_help:=false}
    : ${arg_self_test:=false}

    while (( $# > 0 )); do
        case $1 in
            '-h') ;& '--help') arg_help=true ;;
            '--self-test') arg_self_test=true ;;
            *) echo "Unexpected argument '$1'."; exit 1 ;;
        esac

        shift
    done
}

cli::load "$@"