#!/usr/bin/env CLI_NAME=cli bash-cli-part

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
EOF
}

main() {
    emit::global_variable() {
        sed 's/^declare/declare -g/'
    }
}


emit::function() {
    echo "$1() {"
    emit::indent
    echo "}"
}

cli::main "$@"