#!/usr/bin/env CLI_NAME=cli bash-cli-part
cli::import cli-emit

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}

Description
    Accepts output of 'declare -p' and adds a '-g' to each variable declaration.
EOF
}

main() {
    ::cli::emit::global_variable::inline
}

::cli::emit::global_variable::inline() {
    sed 's/^declare/declare -g/'
}

self_test() {
    foo=42
    declare -p foo \
        | ${CLI_COMMAND[@]} \
        | assert::pipe_eq \
            'declare -g -- foo="42"'
}

cli::main "$@"
