#!/usr/bin/env bash
source $(cli loader)

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    Emit a minimum implementation of initialize.

Description
    Emits a minimum implementation of initialize that supports 
    '-h', '--help', and '--self-test'.

Global Arguments
    --help -h       : Show this message and exit.
    --self-test     : Runs a self test.
EOF
}

initialize() {
    : ${arg_help:=false}
    : ${arg_self_test:=false}

    while (( $# > 0 )); do
        case $1 in
            '-h') ;& '--help') arg_help=true ;;
            '--self-test') arg_self_test=true ;;
            *) echo "Unexpected argument '$1'."; exit 1 ;;
        esac

        shift
    done
}

main() {
    declare -f initialize
}

cli::load "$@"