#!/usr/bin/env bash
source $(cli loader)
cli::import cli_assert

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    Emit a function whose body is the main function of a command.

Description
    Emit a function whose body is the main function of a command.
    The source file containing the fuction to be inlined is read from stdin.

Arguments
    --name   [Required] : The name of the inline function.
    --function          : The name of the function to inline. Default: inline.

Global Arguments
    --help -h    [Flag] : Show this message and exit.
    --self-test  [Flag] : Runs a self test over all commands.

Examples
    Print the main function renmaed to 'say_hi'.
        ${CLI_COMMAND} --name say_hi \\
            <<< "source \\\$(cli loader); inline() { echo 'hi'; }; cli::load"
EOF
}

main() {
    : ${arg_name?'Unexpected lack of inline function name.'}
    : ${arg_function:='inline'}

    (
        # disable loader
        cli() { echo '/dev/null'; }
        cli::import() { return; }
        cli::load() { return; }

        # source file
        source '/dev/stdin'

        # echo and rename main function
        declare -f ${arg_function} | { 
            read
            echo "${arg_name} ()"
            cat
        }
    )
}

self_test() {
    ${CLI_COMMAND} --name say_hi \
        <<< "source \$(cli loader); inline() { echo 'hi'; }; cli::load" \
        | assert::pipe_eq_exact \
            "say_hi ()" \
            "{ " \
            "    echo 'hi'" \
            "}"
}

cli::load "$@"
