#!/usr/bin/env bash
source $(cli loader)

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Summary
    Emit a function whose body is the main function of a command.

Description
    Emit a function whose body is the main function of a command.
    The source file containing the fuction to be inlined is read from stdin.

Arguments
    --name   [Required] : The name of the inline function.
    --function          : The name of the function to inline. Default: inline.

Global Arguments
    --help -h    [Flag] : Show this message and exit.
    --self-test  [Flag] : Runs a self test over all commands.

Examples
    Print the main function renmaed to 'say_hi'.
        ${CLI_COMMAND} --name say_hi \\
            <<< "source \\\$(cli loader); inline() { echo 'hi'; }; cli::main"
EOF
}

inline() {
    : ${arg_name?'Unexpected lack of inline function name.'}
    : ${arg_function:='inline'}

    (
        local -a imports=()

        # disable loader
        cli() { echo '/dev/null'; }
        cli::main() { return; }
        cli::import() { return; }
        cli::import_group() { return; }

        # capture imports upon which the inlined function depends
        cli::import_inline() {
            imports+=( "$*" )
        }

        # source file
        source '/dev/stdin'

        # emit dependencies
        if (( ${#imports[@]} > 0 )); then
            printf 'cli::import %s\n' "${imports[@]}"
        fi

        # emit and rename function
        declare -f ${arg_function} | { 
            read
            echo "${arg_name} ()"
            cat
        }
    )
}

initialize() {
    : ${arg_help:=false}
    : ${arg_self_test:=false}
    : ${arg_name:=}
    : ${arg_function:='inline'}

    while (( $# > 0 )); do
        case $1 in
            '--name') arg_name="${2:-}"; shift ;;
            '--function') arg_function="${2:-}"; shift ;;
            '-h') ;& '--help') arg_help=true ;;
            '--self-test') arg_self_test=true ;;
            *) echo "Unexpected argument '$1'."; exit 1 ;;
        esac

        shift
    done
}

self_test() {
    ${CLI_COMMAND} --name say_hi \
        <<< "source \$(cli loader); inline() { echo 'hi'; }; cli::main" \
        | assert::pipe_eq_exact \
            "say_hi ()" \
            "{ " \
            "    echo 'hi'" \
            "}"
}

cli::main "$@"
