#!/usr/bin/env bash
source $(cli loader)
cli::import cli emit .group

help() {
    cat << EOF
Command
    cli emit source : emit a function containing a library's source

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Emit a function that defines the source emitted by 'cli initialize'
        cli emit source --cli "cli initialize"
EOF
}

main() (
    ${arg_cli} \
        | emit::function "$(cli::emit::library_name "${arg_cli}" 'source')"
)

cli::load "$@"