#!/usr/bin/env bash
source $(cli loader)
cli::import cli emit .group

help() {
    cat << EOF
Command
    cli emit subproc

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Exmpales
    Emit 'cli initialize' command as a subproc 'cli::initialize'
        cli emit subproc --cli "cli initialize"
EOF
}

main() (
    ${arg_cli} '---print' \
        | emit::file \
        | emit::subproc "$(cli::emit::library_name ${arg_cli})"; \
)

cli::load "$@"