#!/usr/bin/env CLI_NAME=cli bash-cli

help() {
    cat << EOF
Command
    ${CLI_COMMAND[@]}
    
Summary
    Emit predicate 'is_group' for a cli.

Arguments
    --name -n    [Required] : Name of the function. 
                              Default: cli::shim::is_group. 
EOF
    cat << EOF

Examples
    Emit a predicate that test if a path is a group.
        cli find --cli cli --type g \
            | cli emit reflection is-group
EOF
}

main() (
    while read; do cli::emit::library_name ${REPLY}; done \
        | emit::function_contains "${arg_name}"
)

cli::main "$@"