#!/usr/bin/env bash
source $(cli loader)
cli::import cli emit .group

help() {
    cat << EOF
Command
    ${CLI_PATH}
    
Summary
    Emit predicate 'is_group' for a cli.

Arguments
    --name -n    [Required] : Name of the function. 
                              Default: cli::shim::is_group. 

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    Emit a predicate that test if a path is a group.
        cli find --cli cli --type g \
            | cli emit reflection is-group
EOF
}

main() (
    while read; do cli::emit::library_name ${REPLY}; done \
        | emit::function_contains "${arg_name}"
)

cli::load "$@"