#!/usr/bin/env bash
source $(cli loader)
cli::import cli emit reflection .group

help() {
    cat << EOF
Command
    cli emit reflection list : emit function 'list' for a cli.
    
Summary
    Emit a function that lists commands and groups of a group 
    encoded as a library name.

Arguments
    --cli -c     [Required] : Name of the cli.

Global Arguments
    --help -h        [Flag] : Show this message and exit.
    --self-test      [Flag] : Runs a self test.

Examples
    cli emit reflection list --cli cli
EOF
}

list_cases() {
    $@ \
        | awk '{print "echo", $1, $2}' \
        | emit::case "$(cli::emit::library_name $@)"

    $@ \
        | awk '$1 == "g" {print $2}' \
        | while read; do list_cases "$@" "${REPLY}"; done
}

main() (
    list_cases "${arg_cli}" \
        | emit::case_statement '$@' \
        | emit::function 'cli::shim::list'
)

cli::load "$@"