#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import cli path dir
cli::import cli path name

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}

Summary
    Set a variable to the cache directory given the path to a command.

Arguments
    Argument $1 is the name of the variable to set.

    Argument $2 is the path to the command whose cache directory will be
    assigned to the variable named by $1.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::cache::path::inline() {
    local -n REPLY_REF=$1
    shift

    local name
    ::cli::path::name::inline name "$1"

    local dir
    ::cli::path::dir::inline dir "$1"

    REPLY_REF="${dir}/.cli/${name}"
}

self_test() {
    path() {
        local REPLY
        ::cli::cache::path::inline REPLY "$@"
        echo "${REPLY}"
    }

    [[ "$(path foo/bar)" == 'foo/.cli/bar' ]] || cli::assert
}
