#!/usr/bin/env bash
source $(cli loader ---exports)
cli::import_group
cli::import cli-assert

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND}

Summary
    Read from stdin and write to a temp file that is moved to a cache path.

Description
    The loader caches results, like generation of the initialize function
    from a source file's help, and uses this function to atomically place
    a cache file. The content is read from stdin, written to a temp file,
    and then that temp file is moved to the cache path. 

Arguments
    --cache -c    [Required] : Path to the cache.
EOF
}

cli::meta::declare() {
    cli::meta::add_required 'cache'
}

cli::cache::put::inline() {
    mkdir -p "${arg_cache%/*}"

    # read content into temp file and then atomically update cache
    local temp_path=$(mktemp "/tmp/cli.cache.put.XXXXXX")
    cat > "${temp_path}"
    mv "${temp_path}" "${arg_cache}"
}

self_test() {
    local cache_dir='/tmp/cache_dir'
    local cache_path="${cache_dir}/cache"

    echo 'content' \
        | cli cache put --cache "${cache_path}"

    cat "${cache_path}" \
        | assert::pipe_eq \
            'content'

    rm "${cache_path}"
    rmdir "${cache_dir}"
}

cli::main "$@"
