#!/usr/bin/env CLI_NAME=cli bash-cli
cli::import cli path dir
cli::import cli temp file

help() {
    cat << EOF | cli::help::global
Command
    ${CLI_COMMAND[@]}

Summary
    Copy stdin to a temp file and then move the file to a cache path.

Description
    Argument $1 is the path to replace with the content read from stdin.
EOF
}

cli::meta::declare() {
    cli::meta::allow_positional
}

::cli::cache::put::inline() {
    local CACHE="$1"

    local DIR
    ::cli::path::dir::inline DIR "${CACHE}"
    mkdir -p "${DIR}"

    local TEMP
    ::cli::temp::file::inline TEMP
    cat > "${TEMP}"

    mv "${TEMP}" "${CACHE}"
}

self_test() {
    local CACHE
    cli::temp::file CACHE
    rm "${CACHE}"

    local DIR="$(dirname "${CACHE}")"

    echo 'content' \
        | ::cli::cache::put::inline "${CACHE}"

    [[ -f "${CACHE}" ]] || cli::assert
    diff "${CACHE}" - <<< 'content' || cli::assert
}
